### ISSUE TITLE
Python I/O failures produce SystemError in ForwardSDMolSupplier and SDWriter

### ISSUE THREAD

**Issue by adalke** [rdkit/rdkit#1065]
The ForwardSDMolSupplier and SDWriter implementations do not propagate errors when used with a Python object which fails to read/write as expected. It looks like there's a missing call to reset or at least forward the exception object. Here are some examples:
- The SDWriter must be a StringIO; BytesIO causes an uncaught Unicode error, which is also seen during the auto-flush in the finalizer.

```
>>> from rdkit import Chem
>>> from io import BytesIO
>>> writer = Chem.SDWriter(BytesIO())
>>> writer.write(Chem.MolFromSmiles("C"))
>>> writer.flush()
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <Boost.Python.function object at 0x102919aa0> returned a result with an error set
```

For even more fun, since the flush() fails, the finalizer will also fail:

```
>>> del writer
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

SystemError: PyEval_EvalFrameEx returned a result with an error set
```
- This can also happen if the output is in an encoding which doesn't support one of the output Unicode points:

```
>>> mol.SetProp("country", "España")
>>> writer = Chem.SDWriter(open("tmp.sdf", "w", encoding="ascii"))
>>> writer.write(mol)
>>> writer.close()
UnicodeEncodeError: 'ascii' codec can't encode character '\xf1' in position 246: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <Boost.Python.function object at 0x102919b10> returned a result with an error set
```

To be cruel, replace the SetProp() value of "España" with b"\xff", which is not a valid utf-8 representation of a string.
- In the "Doctor, doctor, it hurts when I hit myself with a hammer" department, don't close the underlying Python file before you're done with it:

```
>>> f = StringIO()
>>> writer = Chem.SDWriter(f)
>>> f.close()
>>> writer.write(Chem.MolFromSmiles("C"))
>>> writer.flush()
ValueError: I/O operation on closed file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <Boost.Python.function object at 0x102919aa0> returned a result with an error set
>>> del writer
ValueError: I/O operation on closed file

During handling of the above exception, another exception occurred:

SystemError: PyEval_EvalFrameEx returned a result with an error set
```

(I totally expect that to fail. I don't expect to have a SystemError.)
- There are similar limitations in ForwardSDMolSupplier. It really wants a BytesIO, not a StringIO, and will double-exception if you give it a StringIO:

```
>>> molblock = Chem.MolToMolBlock(Chem.MolFromSmiles("C"))
>>> next(Chem.ForwardSDMolSupplier(io.StringIO(molblock)))
[00:48:17] Unexpected error hit on line 1
[00:48:17] ERROR: moving to the begining of the next molecule
TypeError: expected bytes, str found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <Boost.Python.function object at 0x102917f10> returned a result with an error set
```
- There's a similar failure if the Python file is closed while the supplier thinks its open and tries to write to it.

**Comment by greglandrum** [comment]
This is definitely a bug and it's almost certainly fixable.
Doing so, however, isn't going to be particularly pleasant.
So before I embark upon that task, a question to you: how important do you think this bug is?

**Comment by adalke** [comment]
The lowest level of importance. It's a dotted-i/crossed-t sort of thing. It will only affect people who pass in a Python file object, which isn't that common (and was a feature I believe I requested?), and a web search for the error message should bring someone stuck on the problem to this page, with enough info for how to fix the problem.

**Comment by greglandrum** [comment]
Ok. I'm very glad to hear that. I'll flag it as a bug and leave it open, but not assign it to any milestone for now.
If at some point I'm feeling particularly brave, I'll try and actually fix this.

**Comment by halx** [comment]
Looks like this bug is still there... :grin:

But it seems this can be solved with an explicit encoding to open().  So, borrowing from Andrew's example above

`writer = Chem.SDWriter(open("tmp.sdf", "w", encoding="utf8"))
`

seems to be working fine in the problem case I am having.

```
Skipping writing molecule XYZZ to /scratch/input.sdf due to error:
'latin-1' codec can't encode character '\u03b1' in position 772: ordinal not in range(256)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b1' in position 772: ordinal not in range(256)
```
