### ISSUE TITLE
rdkit with inchi support fails in some cases with Boost.Python.ArgumentError:

### ISSUE THREAD

**Issue by mestia** [rdkit/rdkit#1790]
**rdkit built with inchi support in some cases fails **

system information
Tried both on Debian testing and Ubuntu Xenial.
In first case boost version is 1.62, on Xenial 1.58
rdkit is built with inchi support (-DRDK_BUILD_INCHI_SUPPORT=ON)

- RDKit Version: '2017.09.3'
- Platform: Debian/testing, Ubuntu/Xenial

This code:

```
from rdkit import Chem
smiles = "OP(=O)(OC[C@H]1O[C@H]2[C@H]3[C@@H]1O[Mg](O3)O[P@](=O)(O[P@@](=O)(O2)O)O)O"
m = Chem.MolFromSmiles(smiles)
ik = Chem.MolToInchi(m)
```

produces this error:

```
>>> ik = Chem.MolToInchi(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/rdkit/Chem/inchi.py", line 149, in MolToInchi
    treatWarningAsError=treatWarningAsError)
  File "/usr/lib/python3/dist-packages/rdkit/Chem/inchi.py", line 109, in MolToInchiAndAuxInfo
    inchi, retcode, message, logs, aux = rdinchi.MolToInchi(mol, options)
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdinchi.MolToInchi(NoneType, str)
did not match C++ signature:
    MolToInchi(RDKit::ROMol mol, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > options='')
```
Any hint why it happens? 
Thanks!

**Comment by greglandrum** [comment]
The clue is the error message you get when you try to parse the SMILES:
```
In [3]: m = Chem.MolFromSmiles(smiles)
[08:05:00] Explicit valence for atom # 11 Mg, 3, is greater than permitted
```
When you have unreasonable valences in molecules, the RDKit generates an error (show above) and returns `None` for the molecule:
```
In [4]: m is None
Out[4]: True
```

**Comment by mestia** [comment]
I see. Thank you a lot for the explanation!
