### ISSUE TITLE
RDKit import failure caused by Boost incompatibility.

### ISSUE THREAD

**Issue by delta2323** [rdkit/rdkit#1963]
I installed RDkit version 2018.03.2.0 with conda in an environment which has Python 3.6.6. I could install it, but could not import, complaining that `libboost_python3.so` is not found. It seems conda installs Boost 1.67 along with RDKit, although RDKit requires 1.65. Similar problem occurred when I tried Python 2.7.14. The problem did not occur when I used Python 3.5.5 and 3.6.5 (installed boost version are 1.65 in those cases).

If I downgrade Boost version to 1.65, I can import RDKit successfully. But I report the issue because it seems unfavorable behavior to me.

# Versions

Host
- Ubuntu 16.04
- conda 4.5.8

Conda environment
- Python  3.6.6
- RDkit 2018.03.2.0
- Boost 1.67.0

# Commands and logs

```
%conda create -n rdkit-boost-imcompat python=3.6
Solving environment: done

## Package Plan ##

  environment location: /home/delta/.pyenv/versions/anaconda3-4.3.0/envs/rdkit-boost-imcompat

  added / updated specs: 
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sqlite-3.24.0              |       h84994c4_0         1.8 MB
    python-3.6.6               |       hc3d631a_0        29.4 MB
    setuptools-39.2.0          |           py36_0         551 KB
    ------------------------------------------------------------
                                           Total:        31.7 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.03.07-0           
    certifi:         2018.4.16-py36_0       
    libedit:         3.1.20170329-h6b74fdf_2
    libffi:          3.2.1-hd88cf55_4       
    libgcc-ng:       7.2.0-hdf63c60_3       
    libstdcxx-ng:    7.2.0-hdf63c60_3       
    ncurses:         6.1-hf484d3e_0         
    openssl:         1.0.2o-h20670df_0      
    pip:             10.0.1-py36_0          
    python:          3.6.6-hc3d631a_0       
    readline:        7.0-ha6073c6_4         
    setuptools:      39.2.0-py36_0          
    sqlite:          3.24.0-h84994c4_0      
    tk:              8.6.7-hc745277_3       
    wheel:           0.31.1-py36_0          
    xz:              5.2.4-h14c3975_4       
    zlib:            1.2.11-ha838bed_2      

Proceed ([y]/n)? y


Downloading and Extracting Packages
sqlite-3.24.0        |  1.8 MB | ########################################################################################################################################################################### | 100% 
python-3.6.6         | 29.4 MB | ########################################################################################################################################################################### | 100% 
setuptools-39.2.0    |  551 KB | ########################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate rdkit-boost-imcompat
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

```
%conda install -c rdkit rdkit        
Solving environment: done

## Package Plan ##

  environment location: /home/delta/.pyenv/versions/anaconda3-4.3.0/envs/rdkit-boost-imcompat

  added / updated specs: 
    - rdkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    six-1.11.0                 |           py36_1          21 KB
    mkl-2018.0.3               |                1       198.7 MB
    fontconfig-2.13.0          |       h9420a91_0         291 KB
    mkl_fft-1.0.2              |   py36h651fb7a_0         141 KB
    cairo-1.14.12              |       h8948797_3         1.3 MB
    pandas-0.23.3              |   py36h04863e7_0        10.1 MB
    mkl_random-1.0.1           |   py36h4414c95_1         373 KB
    freetype-2.9.1             |       h8a8886c_0         821 KB
    intel-openmp-2018.0.3      |                0         705 KB
    numpy-1.14.5               |   py36h1b885b7_4          35 KB
    py-boost-1.67.0            |   py36h04863e7_4         302 KB
    libuuid-1.0.3              |       h1bed415_2          16 KB
    pillow-5.1.0               |   py36heded4f4_0         581 KB
    libboost-1.67.0            |       h46d08c1_4        20.9 MB
    numpy-base-1.14.5          |   py36hdbf6ddf_4         4.1 MB
    pytz-2018.5                |           py36_0         232 KB
    ------------------------------------------------------------
                                           Total:       238.5 MB

The following NEW packages will be INSTALLED:

    blas:            1.0-mkl                         
    bzip2:           1.0.6-h14c3975_5                
    cairo:           1.14.12-h8948797_3              
    fontconfig:      2.13.0-h9420a91_0               
    freetype:        2.9.1-h8a8886c_0                
    glib:            2.56.1-h000015b_0               
    icu:             58.2-h9c2bf20_1                 
    intel-openmp:    2018.0.3-0                      
    jpeg:            9b-h024ee3a_2                   
    libboost:        1.67.0-h46d08c1_4               
    libgfortran-ng:  7.2.0-hdf63c60_3                
    libpng:          1.6.34-hb9fc6fc_0               
    libtiff:         4.0.9-he85c1e1_1                
    libuuid:         1.0.3-h1bed415_2                
    libxcb:          1.13-h1bed415_1                 
    libxml2:         2.9.8-h26e45fe_1                
    mkl:             2018.0.3-1                      
    mkl_fft:         1.0.2-py36h651fb7a_0            
    mkl_random:      1.0.1-py36h4414c95_1            
    numpy:           1.14.5-py36h1b885b7_4           
    numpy-base:      1.14.5-py36hdbf6ddf_4           
    olefile:         0.45.1-py36_0                   
    pandas:          0.23.3-py36h04863e7_0           
    pcre:            8.42-h439df22_0                 
    pillow:          5.1.0-py36heded4f4_0            
    pixman:          0.34.0-hceecf20_3               
    py-boost:        1.67.0-py36h04863e7_4           
    python-dateutil: 2.7.3-py36_0                    
    pytz:            2018.5-py36_0                   
    rdkit:           2018.03.2.0-py36h6bb024c_1 rdkit
    six:             1.11.0-py36_1                   

Proceed ([y]/n)? y


Downloading and Extracting Packages
six-1.11.0           |   21 KB | ########################################################################################################################################################################### | 100% 
mkl-2018.0.3         | 198.7 MB | ########################################################################################################################################################################## | 100% 
fontconfig-2.13.0    |  291 KB | ########################################################################################################################################################################### | 100% 
mkl_fft-1.0.2        |  141 KB | ########################################################################################################################################################################### | 100% 
cairo-1.14.12        |  1.3 MB | ########################################################################################################################################################################### | 100% 
pandas-0.23.3        | 10.1 MB | ########################################################################################################################################################################### | 100% 
mkl_random-1.0.1     |  373 KB | ########################################################################################################################################################################### | 100% 
freetype-2.9.1       |  821 KB | ########################################################################################################################################################################### | 100% 
intel-openmp-2018.0. |  705 KB | ########################################################################################################################################################################### | 100% 
numpy-1.14.5         |   35 KB | ########################################################################################################################################################################### | 100% 
py-boost-1.67.0      |  302 KB | ########################################################################################################################################################################### | 100% 
libuuid-1.0.3        |   16 KB | ########################################################################################################################################################################### | 100% 
pillow-5.1.0         |  581 KB | ########################################################################################################################################################################### | 100% 
libboost-1.67.0      | 20.9 MB | ########################################################################################################################################################################### | 100% 
numpy-base-1.14.5    |  4.1 MB | ########################################################################################################################################################################### | 100% 
pytz-2018.5          |  232 KB | ########################################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

```
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/delta/.pyenv/versions/anaconda3-4.3.0/envs/rdkit-boost-imcompat/lib/python3.6/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: libboost_python3.so.1.65.1: cannot open shared object file: No such file or directory
```

**Comment by greglandrum** [comment]
You're absolutely right that this should be fixed, but this isn't the right repo for the bug report.

This is a duplicate with the following `conda-rdkit` bug:
https://github.com/rdkit/conda-rdkit/issues/71

**Comment by delta2323** [comment]
Thank you for your reply and sorry for not checking the earlier issues. I'll close the issue.

**Comment by greglandrum** [comment]
no worries, it's not immediately obvious where bugs should be reported. Thanks for going to the trouble to create such a detailed and complete bug report!
