### ISSUE TITLE
rkit compiled for python 2.7 wont run

### ISSUE THREAD

**Issue by SRaent** [rdkit/rdkit#2033]
I am using Manjaro I3 (Arch) and compile rdkit from source as described here https://www.rdkit.org/docs/Install.html
I also installed boost as was described (version boost_1_67_0).
i installed rdkit fro python 2.7, by using the command: 
"cmake -D PYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so -D PYTHON_INCLUDE_DIR=/usr/include/python2.7/ -D PYTHON_EXECUTABLE=/usr/bin/python2.7 -DBOOST_ROOT=/usr/local/boost_1_67_0 .."

- RDKit Version: rdkit-Release_2018_03_4

"import rdkit" in python 2.7 produces:
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moritz/rdkit-Release_2018_03_4/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: libRDKitRDBoost.so.1: cannot open shared object file: No such file or directory

**Comment by greglandrum** [comment]
I'm guessing that the problem is that you haven't set your LD_LIBRARY_PATH to point to `$RDBASE/lib`

-greg

**Comment by SRaent** [comment]
in the cmake command?

**Comment by greglandrum** [comment]
No, in the shell where you are running python.
The environment variables you need to set are described here: https://www.rdkit.org/docs/Install.html#building-the-rdkit

**Comment by greglandrum** [comment]
And just a general comment: unless you have a specific reason to want to compile the RDKit from source, it's almost always easier to install/use it from inside anaconda python.

**Comment by SRaent** [comment]
i tried installing it with miniconda and it did not work.
i executed LD_LIBRARY_PATH=/.../rdkit-Release_2018_03_4/lib/
and it did not change a thing.
what i forgot to mention in the original post is, that i have to run:
"import sys"
"sys.path.append("$RDBASE/")"
otherwise python just sayes : 
">>> rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'rdkit' is not defined"

**Comment by SRaent** [comment]
i recompiled the whole thing with the environment variables set correctly and i still get the same error

**Comment by SRaent** [comment]
is there a support page where i can ask for help or something? i have no idea what i am doing wrong. i checked the enviroment variables twice and recompiled everything now.

**Comment by greglandrum** [comment]
You could try the rdkit-discuss mailing list (https://sourceforge.net/projects/rdkit/lists/rdkit-discuss). Things like this aren't easy to diagnose remotely

But if you installed the rdkit with "conda install" into a conda environment, activated that environment, and it still didn't work then something deeper is going on. What's the error message there?
