### ISSUE TITLE
AssignAtomChiralTagsFromStructure can cause MolToMolBlock to fail

### ISSUE THREAD

**Issue by coleb** [rdkit/rdkit#2227]
**Description:**

AssignAtomChiralTagsFromStructure assigns stereochemistry to sulfones that eventually causes MolToMolBlock to fail because it can't assign wedge/hash bonds. 

```
import rdkit
print(rdkit.__version__)
from rdkit import Chem
from rdkit.Chem import AllChem

mol = Chem.MolFromSmiles('O=[S@](C1CCCCC1)S(=O)(=O)S(=O)(=O)[C@@H]1C[C@@H]1C1CCCCC1')
withHs = Chem.AddHs(mol)
AllChem.EmbedMultipleConfs(withHs, numConfs=1) #, params=AllChem.ETKDG())
Chem.AssignAtomChiralTagsFromStructure(withHs)
for atom in withHs.GetAtoms():
    if atom.GetChiralTag() != Chem.rdchem.ChiralType.CHI_UNSPECIFIED:
        print(atom.GetAtomicNum(), atom.GetChiralTag())
Chem.MolToMolBlock(withHs)
```

This will fail with the following error:
```
2018.09.1
16 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
16 CHI_TETRAHEDRAL_CW
16 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CW
[21:04:56] 

****
Invariant Violation
no eligible neighbors for chiral center
Violation occurred on line 515 in file /Users/travis/miniconda3/conda-bld/rdkit_1540561397247/work/Code/GraphMol/FileParsers/MolFileStereochem.cpp
Failed Expression: nbrScores.size()
****

Traceback (most recent call last):
  File "rdkit_mol_file_stereochem_problem.py", line 13, in <module>
    Chem.MolToMolBlock(withHs)
RuntimeError: Invariant Violation
	no eligible neighbors for chiral center
	Violation occurred on line 515 in file Code/GraphMol/FileParsers/MolFileStereochem.cpp
	Failed Expression: nbrScores.size()
	RDKIT: 2018.09.1
	BOOST: 1_68 
```

If you trace that invariant check down you will find this rather amusing comment: 

```
INT_MAP_INT pickBondsToWedge(const ROMol &mol) {
...
    // There's still one situation where this whole thing can fail: an unlucky                                                                                          
    // situation where all neighbors of all neighbors of an atom are chiral and                                                                                         
    // that atom ends up being the last one picked for stereochem assignment.                                                                                           
    //                                                                                                                                                                  
    // We'll catch that as an error here and hope that it's as unlikely to occur                                                                                        
    // as it seems like it is. (I'm going into this knowing that it's bound to                                                                                          
    // happen; I'll kick myself and do the hard solution at that point.)                                                                                                
    CHECK_INVARIANT(nbrScores.size(),
                    "no eligible neighbors for chiral center");
...
```

Note, this only started failing in this more catastrophic way in RDKit 2017:

```
$ python rdkit_mol_file_stereochem_problem.py
2015.09.2
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
$ python rdkit_mol_file_stereochem_problem.py
2016.09.4
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
$ python rdkit_mol_file_stereochem_problem.py
2017.09.1
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
(16, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CCW)
(6, rdkit.Chem.rdchem.ChiralType.CHI_TETRAHEDRAL_CW)
[21:15:42] 

****
Invariant Violation
no eligible neighbors for chiral center
Violation occurred on line 504 in file /Users/glandrum/anaconda/conda-bld/rdkit_1507440674398/work/Code/GraphMol/FileParsers/MolFileStereochem.cpp
Failed Expression: nbrScores.size()
****

Traceback (most recent call last):
  File "rdkit_mol_file_stereochem_problem.py", line 13, in <module>
    Chem.MolToMolBlock(withHs)
RuntimeError: Invariant Violation
	no eligible neighbors for chiral center
	Violation occurred on line 504 in file Code/GraphMol/FileParsers/MolFileStereochem.cpp
	Failed Expression: nbrScores.size()
	RDKIT: 2017.09.1
	BOOST: 1_63
$ python rdkit_mol_file_stereochem_problem.py
2018.09.1
16 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
16 CHI_TETRAHEDRAL_CW
16 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CW
[21:14:36] 

****
Invariant Violation
no eligible neighbors for chiral center
Violation occurred on line 515 in file /Users/travis/miniconda3/conda-bld/rdkit_1540561397247/work/Code/GraphMol/FileParsers/MolFileStereochem.cpp
Failed Expression: nbrScores.size()
****

Traceback (most recent call last):
  File "rdkit_mol_file_stereochem_problem.py", line 13, in <module>
    Chem.MolToMolBlock(withHs)
RuntimeError: Invariant Violation
	no eligible neighbors for chiral center
	Violation occurred on line 515 in file Code/GraphMol/FileParsers/MolFileStereochem.cpp
	Failed Expression: nbrScores.size()
	RDKIT: 2018.09.1
	BOOST: 1_68
```

Note, in 2016 the definition of sulfur stereochemistry seemed to change. All the sulfurs became stereo centers, previously only 2 of them were, but that still doesn't seem correct. 

So the fix we need appears to be two-fold: don't consider sulfones as stereo centers; make pickBondsToWedge more robust to crowded stereo environments.

**Comment by greglandrum** [comment]
Yeah, the sulfones definitely should not be stereocenters... that's clearly wrong. I'm going to create a second issue for that.

Also: I had forgotten that comment. Amusing to see that. :-)

**Comment by coleb** [comment]
Attaching another example I just found of this problem that doesn't rely on the incorrect perception of sulfone stereochemistry: `C/N=[S@@H](=O)/[C@H]([C@H]1CCc2ccccc2C1)[C@@H]1CCCNC1=O` 

Though I can't trigger it when using ETKDG's conformer generator, this test will have to come from an SDF file. 

```
In [12]: mol = Chem.MolFromMolFile("invented.sdf")

In [13]: Chem.AssignAtomChiralTagsFromStructure(mol)

In [14]:     for atom in mol.GetAtoms():
    ...:         if atom.GetChiralTag() != Chem.rdchem.ChiralType.CHI_UNSPECIFIED:
    ...:             print(atom.GetAtomicNum(), atom.GetChiralTag())
    ...:         
16 CHI_TETRAHEDRAL_CW
6 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CCW
6 CHI_TETRAHEDRAL_CW

In [15]: Chem.MolToMolBlock(mol)
[17:14:24] 

****
Invariant Violation
no eligible neighbors for chiral center
Violation occurred on line 515 in file /Users/travis/miniconda3/conda-bld/rdkit_1540561397247/work/Code/GraphMol/FileParsers/MolFileStereochem.cpp
Failed Expression: nbrScores.size()
****

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-f2b6a55e870d> in <module>()
----> 1 Chem.MolToMolBlock(mol)

RuntimeError: Invariant Violation
	no eligible neighbors for chiral center
	Violation occurred on line 515 in file Code/GraphMol/FileParsers/MolFileStereochem.cpp
	Failed Expression: nbrScores.size()
	RDKIT: 2018.09.1
	BOOST: 1_68

```

[invented.sdf.txt](https://github.com/rdkit/rdkit/files/2784798/invented.sdf.txt)

**Comment by lonngxiang** [comment]
The same error, how to solve?

```
    w.write(mol)
RuntimeError: Invariant Violation
        no eligible neighbors for chiral center
        Violation occurred on line 213 in file Code\GraphMol\FileParsers\MolFileStereochem.cpp
        Failed Expression: nbrScores.size()
        RDKIT: 2022.09.1
        BOOST: 1_75
```

**Comment by greglandrum** [comment]
@lonngxiang : we can't help if you don't provide the sample input which caused the problem you are seeing.

**Comment by pkrezel** [comment]
Hi,

I got the same problem. I send you a pickle file of rdkit molecules that generates this problem.
I created a pdb created from them also.

Pascal KREZEL
[Lmol_error.zip](https://github.com/rdkit/rdkit/files/10361160/Lmol_error.zip)
