### ISSUE TITLE
ctest shows Failed results on Centos7.6

### ISSUE THREAD

**Issue by ChinzoD** [rdkit/rdkit#2249]
**Description:**

- RDKit Version: **2018_09_1 (Q3 2018) Release**
- Platform: **CentOS Linux release 7.6.1810.2.el7.centos.x86_64** 

**1. Installing prerequisites from source**
```
>_ $ yum install cmake3 zlib1g-dev gcc
>_ $ wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
>_ $ tar -xzf boost_1_*
>_ $ cd boost_1_*
>_ $ ./bootstrap.sh --prefix=/opt/boost --with-libraries=serialization
>_ $ ./b2 install --prefix=/opt/boost

```
**2. Building the RDKit from source**
```
>_ $ wget https://github.com/rdkit/rdkit/archive/Release_XXXX_XX_X.tar.gz
>_ $ tar zxvf Release_2018_09_1.tar.gz 
>_ $ mkdir /opt/rdkit
>_ $ cp -r rdkit-Release_2018_09_1/* /opt/rdkit
>_ $ export RDBASE=/opt/rdkit
>_ $ cd $RDBASE
>_ $ mkdir build && cd build
>_ $ cmake3 -DPYTHON_LIBRARY=/opt/python3/lib/libpython3.6m.a \ -DPYTHON_INCLUDE_DIR=/opt/python3/include/python3.6m \ -DPYTHON_EXECUTABLE=/usr/bin/python3 \ -DPYTHON_NUMPY_INCLUDE_PATH=/opt/python3/lib/python3.6/site-packages/numpy/core/include \
-DBOOST_ROOT=/opt/boost \
-DBoost_NO_SYSTEM_PATHS=ON \
-DRDK_USE_BOOST_SERIALIZATION=OFF \
-DRDK_BUILD_PYTHON_WRAPPERS=OFF \
-DRDK_BUILD_INCHI_SUPPORT=ON \
-DRDK_BUILD_AVALON_SUPPORT=ON \
-DRDK_BUILD_PGSQL=ON \
-DBoost_USE_STATIC_LIBS=OFF \
-DPostgreSQL_ROOT=/usr/pgsql-10 \
-DPostgreSQL_TYPE_INCLUDE_DIR=/usr/pgsql-10/include/server ..

-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found Catch2 source in /opt/rdkit/External/catch/catch
CATCH: /opt/rdkit/External/catch/catch/single_include
-- Could NOT find InChI in system locations (missing: INCHI_LIBRARY INCHI_INCLUDE_DIR) 
CUSTOM_INCHI_PATH = /opt/rdkit/External/INCHI-API
-- Found InChI software locally
-- Boost version: 1.68.0
-- Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK) (Required is at least version "2.91.0")
Eigen3 not found, disabling the Descriptors3D build.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning (dev) at CMakeLists.txt:360 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PostgreSQL_ROOT is set to:

    /usr/pgsql-10

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PostgreSQL: /usr/lib64/libpq.so (found version "9.2.24") 
== Using strict rotor definition
-- Found MAEParser source in /opt/rdkit/External/CoordGen/maeparser
-- Found coordgenlibs source in /opt/rdkit/External/CoordGen/coordgenlibs
== Making EnumerateLibrary without boost Serialization support
== Making FilterCatalog without boost Serialization support
-- Found PythonInterp: /bin/python (found version "2.7.5") 
== Updating Filters.cpp from pains file
== Done updating pains files
-- Found RapidJSON source in /opt/rdkit/External
CMake Warning (dev) at Code/PgSQL/rdkit/CMakeLists.txt:11 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PostgreSQL_ROOT is set to:

    /usr/pgsql-10

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

postgres: /usr/include;/usr/pgsql-10/include/server

=====================================================================
After building, check
/opt/rdkit/build/Code/PgSQL/rdkit/pgsql_install.sh
for correctness of installation paths. If everything is OK, gain 
administrator privileges, stop the PostgreSQL service, run
/opt/rdkit/build/Code/PgSQL/rdkit/pgsql_install.sh
to install the PostgreSQL RDKit cartridge, then start again
the PostgreSQL service
=====================================================================

-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_LIBRARY


-- Build files have been written to: /opt/rdkit/build


>_ $ make -j 8
>_ $ make install
>_ $ ctest
The following tests FAILED:
	  6 - testDataStructs (ILLEGAL)
	  7 - testFPB (ILLEGAL)
	  8 - testMultiFPB (ILLEGAL)
	 58 - testFingerprints (ILLEGAL)
	 94 - testPgSQL (Failed)
Errors while running CTest
```
After run ctest it show failed test results. Could you please help on that?

**Comment by bp-kelley** [comment]
Try adding this to your cmake line (this is a guess based on the illegal instructions)

```
-DRDK_OPTIMIZE_NATIVE=OFF
```

This turns of the popcnt instruction which those libraries certainly use.  Do you happen to know your processor by the way?

**Comment by ChinzoD** [comment]
Yes. This server has 8 CPUs.

`-DRDK_OPTIMIZE_NATIVE=OFF`

It shows error as below after adding above line

```
The following tests FAILED:
	 94 - testPgSQL (Failed)
Errors while running CTest
```

Created rdkit.pth file (_points to /opt/rdkit dir_) in the current python3 lib directory and tried to import rdkit
```
>_ $ python3
Python 3.6.7 (default, Jan 29 2019, 11:21:46) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rdkit/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ModuleNotFoundError: No module named 'rdkit.rdBase'
>>> from rdkit.Chem import Draw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rdkit/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ModuleNotFoundError: No module named 'rdkit.rdBase'
```

**Comment by UnixJunkie** [comment]
Maybe you can try this script:
https://github.com/rdkit/rdkit/blob/master/Scripts/create_deb_packages.sh
and replace deb by RPM.
I'm not sure it works with python3 though.

**Comment by greglandrum** [comment]
There are a couple of different, possibly unconnected, problems here and it probably helps to discuss them separately.

I'm going to start with the pgsql problems and then we can move onto the Python problems.

When reporting failures from ctest, it really helps to run `ctest --output-on-failure` and then paste in the error messages you see.
In the case of a pgsql failure, it's likely to mention a file that contains the differences between the expected results and what came out of the tests. Could you please paste in the contents of that file?

**Comment by ChinzoD** [comment]
```
      Start 94: testPgSQL
94/94 Test #94: testPgSQL ..........................***Failed    7.32 sec
(using postmaster on Unix socket, default port)
============== dropping database "regression"         ==============
DROP DATABASE
============== creating database "regression"         ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test rdkit-91                 ... FAILED (test process exited with exit code 2)
test props                    ... FAILED (test process exited with exit code 2)
test btree                    ... FAILED (test process exited with exit code 2)
test molgist                  ... FAILED (test process exited with exit code 2)
test bfpgist-91               ... FAILED (test process exited with exit code 2)
test sfpgist                  ... FAILED (test process exited with exit code 2)
test slfpgist                 ... FAILED (test process exited with exit code 2)
test fps                      ... FAILED (test process exited with exit code 2)
test reaction                 ... FAILED (test process exited with exit code 2)
test avalon                   ... FAILED (test process exited with exit code 2)
test inchi                    ... FAILED (test process exited with exit code 2)

========================
 11 of 11 tests failed. 
========================

The differences that caused some tests to fail can be viewed in the
file "/opt/rdkit/build/Code/PgSQL/rdkit/regression.diffs".  A copy of the test summary that you see
above is saved in the file "/opt/rdkit/build/Code/PgSQL/rdkit/regression.out".



95% tests passed, 5 tests failed out of 94

Total Test time (real) = 338.26 sec

The following tests FAILED:
	  6 - testDataStructs (ILLEGAL)
	  7 - testFPB (ILLEGAL)
	  8 - testMultiFPB (ILLEGAL)
	 58 - testFingerprints (ILLEGAL)
	 94 - testPgSQL (Failed)
```

You can get those log files from [here](https://drive.google.com/open?id=1UHDjhoc9zbdDi1TQBAXF2VDjZztG96i4)

**Comment by ChinzoD** [comment]
ctest passed successfully with `-DRDK_OPTIMIZE_NATIVE=OFF`.

`100% tests passed, 0 tests failed out of 94`

CPU info:
```
>_ $ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 23
Model name:            Intel(R) Xeon(R) CPU           E5430  @ 2.66GHz
Stepping:              6
CPU MHz:               2003.000
CPU max MHz:           2670.0000
CPU min MHz:           2003.0000
BogoMIPS:              5320.08
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              6144K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 lahf_lm tpr_shadow vnmi flexpriority dtherm
```

Rdkit import error:
```
# python3
Python 3.6.7 (default, Jan 29 2019, 11:21:46) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit.Chem import Draw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rdkit/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ModuleNotFoundError: No module named 'rdkit.rdBase'
>>> 
```

**Comment by greglandrum** [comment]
Is `/opt/rdkit/` where "make install" put things?

**Comment by ChinzoD** [comment]
Yes. Below commands are the steps that I installed rdkit. 

```
>_ $ wget https://github.com/rdkit/rdkit/archive/Release_XXXX_XX_X.tar.gz
>_ $ tar zxvf Release_2018_09_1.tar.gz 
>_ $ mkdir /opt/rdkit
>_ $ cp -r rdkit-Release_2018_09_1/* /opt/rdkit
>_ $ export RDBASE=/opt/rdkit
>_ $ export LD_LIBRARY_PATH=$RDBASE/lib
>_ $ cd $RDBASE
>_ $ mkdir build && cd build
>_ $ cmake3 -DPYTHON_VERSION_MAJOR=3 \ -DPYTHON_LIBRARY=/opt/python3/lib/libpython3.6m.a \ -DPYTHON_INCLUDE_DIR=/opt/python3/include/python3.6m \ -DPYTHON_EXECUTABLE=/usr/bin/python3 \ -DPYTHON_NUMPY_INCLUDE_PATH=/opt/python3/lib/python3.6/site-packages/numpy/core/include \
-DBOOST_ROOT=/opt/boost \
-DBoost_NO_SYSTEM_PATHS=ON \
-DRDK_USE_BOOST_SERIALIZATION=OFF \
-DRDK_BUILD_PYTHON_WRAPPERS=OFF \
-DRDK_BUILD_INCHI_SUPPORT=ON \
-DRDK_BUILD_AVALON_SUPPORT=ON \
-DRDK_BUILD_PGSQL=ON \
-DBoost_USE_STATIC_LIBS=OFF \
-DPostgreSQL_ROOT=/usr/pgsql-10 \
-DRDK_OPTIMIZE_NATIVE=OFF \
-DPostgreSQL_TYPE_INCLUDE_DIR=/usr/pgsql-10/include/server ..

>_ $ make
>_ $ make install
```

**Comment by greglandrum** [comment]
You turned the python wrappers off when you did the build. That's what `-DRDK_BUILD_PYTHON_WRAPPERS=OFF` does

**Comment by ChinzoD** [comment]
It shows below error when I try to install with `-DRDK_BUILD_PYTHON_WRAPPERS=ON`

```
Could not find the following Boost libraries:
boost_python
```
I tried to install python_boost separately but it didn't help. 

Boost 1.68 installation steps:
```
>_ $ wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
>_ $ tar -xzf boost_1_*
>_ $ cd boost_1_*
>_ $ ./bootstrap.sh --with-python=python3 --with-libraries=python,serialization 
--prefix=/opt/boost
>_ $ ./b2 install --prefix=/opt/boost 
```

**Comment by brndnsy** [comment]
> It shows below error when I try to install with `-DRDK_BUILD_PYTHON_WRAPPERS=ON`
> 
> ```
> Could not find the following Boost libraries:
> boost_python
> ```
> 
> I tried to install python_boost separately but it didn't help.
> 
> Boost 1.68 installation steps:
> 
> ```
> >_ $ wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
> >_ $ tar -xzf boost_1_*
> >_ $ cd boost_1_*
> >_ $ ./bootstrap.sh --with-python=python3 --with-libraries=python,serialization 
> --prefix=/opt/boost
> >_ $ ./b2 install --prefix=/opt/boost 
> ```

did you find a fix?

**Comment by UnixJunkie** [comment]
Why not try:
```bash
pip3 install boost-python3
```

**Comment by brndnsy** [comment]
> Why not try:
> 
> ```shell
> pip3 install boost-python3
> ```

That returns "Could not find a version that satisfies the requirement boost-python3 (from versions: none)" 

I can install it using "pip install pyboost"
