### ISSUE TITLE
getDistanceMatrix throws a type error in Python 3

### ISSUE THREAD

**Issue by John-Videogames** [rdkit/rdkit#2387]
**Description:**

- RDKit Version:
2018.09.1       py37h4a7b924_1000    conda-forge
- Platform:
Linux x86-64

In Python3, the function rdkit.Chem.Fingerprints.ClusterMols.GetDistanceMatrix throws
the following error.
```
Traceback (most recent call last):
  File "./break_getDistanceMatrix.py", line 9, in <module>
    distance_matrix = ClusterMols.GetDistanceMatrix(fingerprints, metric=rdkit.DataStructs.DiceSimilarity)
  File "$(CONDA_PREFIX)/envs/chembl-topology/lib/python3.7/site-packages/rdkit/Chem/Fingerprints/ClusterMols.py", line 42, in GetDistanceMatrix
    res = numpy.zeros((nPts * (nPts - 1) / 2), numpy.float)
TypeError: 'float' object cannot be interpreted as an integer

```
Minimal code to reproduce the issue:
```
import rdkit
from rdkit import Chem
from rdkit.Chem.Fingerprints import ClusterMols
from rdkit.Chem.AllChem import GetMorganFingerprintAsBitVect

mols = [Chem.MolFromSmiles("C1=CC=CC=C1"), Chem.MolFromSmiles("CC1=CC=CC=C1")]
fingerprints = [GetMorganFingerprintAsBitVect(mol,3) for mol in mols]
distance_matrix = ClusterMols.GetDistanceMatrix(fingerprints, metric=rdkit.DataStructs.DiceSimilarity)
```

**Comment by bp-kelley** [comment]
Thanks!  the code should probably be:

```
res = numpy.zeros(int(nPts * (nPts - 1) / 2), numpy.float)
```

in py3, I'll do a quick pr for this.
