### ISSUE TITLE
ctest pythonTestDirChem failed

### ISSUE THREAD

**Issue by jinserk** [rdkit/rdkit#2757]
**Configuration:**

- RDKit Version: 2019.09.1
- Operating system: MacOSX 10.15
- Python version (if relevant): 3.8.0
- Are you using conda? No
- If you are using conda, which channel did you install the rdkit from?
- If you are not using conda: how did you install the RDKit? : Compile from source

**Description:**

I compiled latest RDKit release with Python 3.8.0 but had a failed test as:
```
Start testing: Nov 01 10:34 EDT
----------------------------------------------------------
169/170 Testing: pythonTestDirChem
169/170 Test: pythonTestDirChem
Command: "/Users/jinserk/.pyenv/versions/3.8.0/bin/python" "/Users/jinserk/kyu-dev/rdkit/rdkit/Chem/test_list.py" "--testDir" "/Users/jinserk/kyu-dev/rdkit/rdkit/Chem" "--buildType" "Release"
Directory: /Users/jinserk/kyu-dev/rdkit/build/rdkit
"pythonTestDirChem" start time: Nov 01 10:34 EDT
Output:
----------------------------------------------------------
......
----------------------------------------------------------------------
Ran 6 tests in 0.080s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.032s

OK
....[10:34:45] 

****
Pre-condition Violation
valence not defined for atoms not associated with molecules
Violation occurred on line 290 in file /Users/jinserk/kyu-dev/rdkit/Code/GraphMol/Atom.cpp
Failed Expression: dp_mol
****

.
----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.012s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.012s

OK
......................
----------------------------------------------------------------------
Ran 22 tests in 0.030s

OK
.....s.................ss
----------------------------------------------------------------------
Ran 25 tests in 0.095s

OK (skipped=3)
..s
----------------------------------------------------------------------
Ran 3 tests in 0.139s

OK (skipped=1)
...................................
----------------------------------------------------------------------
Ran 35 tests in 1.069s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.020s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.012s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.044s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.059s

OK
.ss.ss.......
----------------------------------------------------------------------
Ran 13 tests in 0.735s

OK (skipped=4)
.........F....[10:35:03] WARNING: More than one matching pattern found - picking one
[10:35:03] WARNING: More than one matching pattern found - picking one
.[10:35:03] WARNING: More than one matching pattern found - picking one
..
======================================================================
FAIL: testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnitTestMol3D.py", line 218, in testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable
    self.assertEqual(smiles, expected)
AssertionError: Items in the first set but not the second:
'C/C(F)=C/[C@@H](Cl)/C=C(\\Br)[C@H](N)I'
'C/C(F)=C\\[C@H](Cl)/C=C(\\Br)[C@H](N)I'
Items in the second set but not the first:
'C/C(F)=C/[C@H](Cl)/C=C(\\Br)[C@H](N)I'
'C/C(F)=C/[C@@H](Cl)/C=C(/Br)[C@@H](N)I'

----------------------------------------------------------------------
Ran 17 tests in 11.951s

FAILED (failures=1)
........
----------------------------------------------------------------------
Ran 8 tests in 0.091s

OK
....[10:35:07] WARNING: not removing hydrogen atom without neighbors
[10:35:07] WARNING: not removing hydrogen atom without neighbors
[10:35:07] WARNING: not removing hydrogen atom without neighbors
.......
----------------------------------------------------------------------
Ran 11 tests in 3.116s

OK
[10:35:07] WARNING: Omitted undefined stereo
[10:35:07] WARNING: Proton(s) added/removed
.......
----------------------------------------------------------------------
Ran 7 tests in 8.037s

OK

ESC[32mInChI write Summary: 1164 identical, 0 suffix variance, 17 reasonableESC[0m

ESC[32mInChI read Summary: 627 identical, 0 variance, 554 reasonable varianceESC[0m
....
----------------------------------------------------------------------
Ran 4 tests in 1.107s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.253s

OK
.............s..s........
----------------------------------------------------------------------
Ran 25 tests in 2.385s

OK (skipped=2)
F.............[10:35:25] WARNING: More than one matching pattern found - picking one
[10:35:25] WARNING: More than one matching pattern found - picking one
...........
======================================================================
FAIL: EnumerateStereoisomers (rdkit.Chem.EnumerateStereoisomers)
Doctest: rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jinserk/.pyenv/versions/3.8.0/lib/python3.8/doctest.py", line 2196, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
  File "/Users/jinserk/kyu-dev/rdkit/rdkit/Chem/EnumerateStereoisomers.py", line 164, in EnumerateStereoisomers

----------------------------------------------------------------------
File "/Users/jinserk/kyu-dev/rdkit/rdkit/Chem/EnumerateStereoisomers.py", line 286, in rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
Failed example:
    for smi in sorted(Chem.MolToSmiles(x, isomericSmiles=True) for x in isomers):
        print(smi)
Expected:
    F[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)Br
    F[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)Br
    F[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)Br
Got:
    F[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)Br
    F[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)Br
    F[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)Br


----------------------------------------------------------------------
Ran 25 tests in 4.966s

FAILED (failures=1)
..
----------------------------------------------------------------------
Ran 2 tests in 0.049s

OK
..s...
----------------------------------------------------------------------
Ran 6 tests in 0.524s

OK (skipped=1)
.[10:35:27] WARNING: not removing hydrogen atom without neighbors
.[10:35:27] WARNING: not removing hydrogen atom without neighbors
.[10:35:27] WARNING: no name column found on line 1
[10:35:27] WARNING: no name column found on line 2
[10:35:27] WARNING: no name column found on line 3
[10:35:27] WARNING: no name column found on line 4
[10:35:27] WARNING: no name column found on line 5
[10:35:27] WARNING: no name column found on line 6
[10:35:27] WARNING: no name column found on line 7
[10:35:27] WARNING: no name column found on line 8
[10:35:27] WARNING: no name column found on line 9
[10:35:27] WARNING: no name column found on line 10
[10:35:27] WARNING: no name column found on line 11
[10:35:27] WARNING: no name column found on line 12
[10:35:27] WARNING: no name column found on line 13
[10:35:27] WARNING: no name column found on line 14
[10:35:27] WARNING: no name column found on line 15
[10:35:27] WARNING: no name column found on line 16
[10:35:27] WARNING: no name column found on line 17
[10:35:27] WARNING: no name column found on line 18
[10:35:27] WARNING: no name column found on line 19
[10:35:27] WARNING: no name column found on line 20
[10:35:27] WARNING: no name column found on line 21
[10:35:27] WARNING: no name column found on line 22
[10:35:27] WARNING: no name column found on line 23
[10:35:27] WARNING: no name column found on line 24
[10:35:27] WARNING: no name column found on line 25
[10:35:27] WARNING: no name column found on line 26
[10:35:27] WARNING: no name column found on line 27
[10:35:27] WARNING: no name column found on line 28
[10:35:27] WARNING: no name column found on line 29
[10:35:27] WARNING: no name column found on line 30
[10:35:27] WARNING: no name column found on line 31
[10:35:27] WARNING: no name column found on line 32
[10:35:27] WARNING: no name column found on line 33
[10:35:27] WARNING: no name column found on line 34
[10:35:27] WARNING: no name column found on line 35
[10:35:27] WARNING: no name column found on line 36
[10:35:27] WARNING: no name column found on line 37
[10:35:27] WARNING: no name column found on line 38
[10:35:27] WARNING: no name column found on line 39
[10:35:27] WARNING: no name column found on line 40
[10:35:27] WARNING: no name column found on line 41
[10:35:27] WARNING: no name column found on line 42
[10:35:27] WARNING: no name column found on line 43
[10:35:27] WARNING: no name column found on line 44
[10:35:27] WARNING: no name column found on line 45
[10:35:27] WARNING: no name column found on line 46
[10:35:27] WARNING: no name column found on line 47
[10:35:27] WARNING: no name column found on line 48
[10:35:27] WARNING: no name column found on line 49
[10:35:27] WARNING: no name column found on line 50
[10:35:27] WARNING: no name column found on line 51
[10:35:27] WARNING: no name column found on line 52
[10:35:27] WARNING: no name column found on line 53
[10:35:27] WARNING: no name column found on line 54
[10:35:27] WARNING: no name column found on line 55
[10:35:27] WARNING: no name column found on line 56
[10:35:27] WARNING: no name column found on line 57
[10:35:27] WARNING: no name column found on line 58
[10:35:27] WARNING: no name column found on line 59
[10:35:27] WARNING: no name column found on line 60
[10:35:27] WARNING: no name column found on line 61
[10:35:27] WARNING: no name column found on line 62
[10:35:27] WARNING: no name column found on line 63
[10:35:27] WARNING: no name column found on line 64
[10:35:27] WARNING: no name column found on line 65
[10:35:27] WARNING: no name column found on line 66
[10:35:27] WARNING: no name column found on line 67
[10:35:27] WARNING: no name column found on line 68
[10:35:27] WARNING: no name column found on line 69
[10:35:27] WARNING: no name column found on line 70
[10:35:27] WARNING: no name column found on line 71
[10:35:27] WARNING: no name column found on line 72
[10:35:27] WARNING: no name column found on line 73
[10:35:27] WARNING: no name column found on line 74
[10:35:27] WARNING: no name column found on line 75
[10:35:27] WARNING: no name column found on line 76
[10:35:27] WARNING: no name column found on line 77
[10:35:27] WARNING: no name column found on line 78
[10:35:27] WARNING: no name column found on line 79
[10:35:27] WARNING: no name column found on line 80
[10:35:27] WARNING: no name column found on line 81
[10:35:27] WARNING: no name column found on line 82
[10:35:27] WARNING: no name column found on line 83
[10:35:27] WARNING: no name column found on line 84
[10:35:27] WARNING: no name column found on line 85
[10:35:27] WARNING: no name column found on line 86
[10:35:27] WARNING: no name column found on line 87
[10:35:27] WARNING: no name column found on line 88
[10:35:27] WARNING: no name column found on line 89
[10:35:27] WARNING: no name column found on line 90
[10:35:27] WARNING: no name column found on line 91
[10:35:27] WARNING: no name column found on line 92
[10:35:27] WARNING: no name column found on line 93
[10:35:27] WARNING: no name column found on line 94
[10:35:27] WARNING: no name column found on line 95
[10:35:27] WARNING: no name column found on line 96
[10:35:27] WARNING: no name column found on line 97
[10:35:27] WARNING: no name column found on line 98
[10:35:27] WARNING: no name column found on line 99
[10:35:27] WARNING: no name column found on line 100
[10:35:27] WARNING: no name column found on line 101
[10:35:27] WARNING: no name column found on line 102
[10:35:27] WARNING: no name column found on line 103
[10:35:27] WARNING: no name column found on line 104
[10:35:27] WARNING: no name column found on line 105
[10:35:27] WARNING: no name column found on line 106
[10:35:27] WARNING: no name column found on line 107
[10:35:27] WARNING: no name column found on line 108
[10:35:27] WARNING: no name column found on line 109
[10:35:27] WARNING: no name column found on line 110
[10:35:27] WARNING: no name column found on line 111
[10:35:27] WARNING: no name column found on line 112
[10:35:27] WARNING: no name column found on line 113
[10:35:27] WARNING: no name column found on line 114
[10:35:27] WARNING: no name column found on line 115
[10:35:27] WARNING: no name column found on line 116
[10:35:27] WARNING: no name column found on line 117
[10:35:27] WARNING: no name column found on line 118
[10:35:27] WARNING: no name column found on line 119
[10:35:27] WARNING: no name column found on line 120
[10:35:27] WARNING: no name column found on line 121
[10:35:27] WARNING: no name column found on line 122
[10:35:27] WARNING: no name column found on line 123
[10:35:27] WARNING: no name column found on line 124
[10:35:27] WARNING: no name column found on line 125
[10:35:27] WARNING: no name column found on line 126
[10:35:27] WARNING: no name column found on line 127
[10:35:27] WARNING: no name column found on line 128
[10:35:27] WARNING: no name column found on line 129
[10:35:27] WARNING: no name column found on line 130
[10:35:27] WARNING: no name column found on line 131
[10:35:27] WARNING: no name column found on line 132
[10:35:27] WARNING: no name column found on line 133
[10:35:27] WARNING: no name column found on line 134
[10:35:27] WARNING: no name column found on line 135
[10:35:27] WARNING: no name column found on line 136
[10:35:27] WARNING: no name column found on line 137
[10:35:27] WARNING: no name column found on line 138
[10:35:27] WARNING: no name column found on line 139
[10:35:27] WARNING: no name column found on line 140
[10:35:27] WARNING: no name column found on line 141
[10:35:27] WARNING: no name column found on line 142
[10:35:27] WARNING: no name column found on line 143
[10:35:27] WARNING: no name column found on line 144
[10:35:27] WARNING: no name column found on line 145
[10:35:27] WARNING: no name column found on line 146
[10:35:27] WARNING: no name column found on line 147
[10:35:27] WARNING: no name column found on line 148
[10:35:27] WARNING: no name column found on line 149
[10:35:27] WARNING: no name column found on line 150
[10:35:27] WARNING: no name column found on line 151
[10:35:27] WARNING: no name column found on line 152
[10:35:27] WARNING: no name column found on line 153
[10:35:27] WARNING: no name column found on line 154
[10:35:27] WARNING: no name column found on line 155
[10:35:27] WARNING: no name column found on line 156
[10:35:27] WARNING: no name column found on line 157
[10:35:27] WARNING: no name column found on line 158
[10:35:27] WARNING: no name column found on line 159
[10:35:27] WARNING: no name column found on line 160
[10:35:27] WARNING: no name column found on line 161
[10:35:27] WARNING: no name column found on line 162
[10:35:27] WARNING: no name column found on line 163
[10:35:27] WARNING: no name column found on line 164
[10:35:27] WARNING: no name column found on line 165
[10:35:27] WARNING: no name column found on line 166
[10:35:27] WARNING: no name column found on line 167
[10:35:27] WARNING: no name column found on line 168
[10:35:27] WARNING: no name column found on line 169
[10:35:27] WARNING: no name column found on line 170
[10:35:27] WARNING: no name column found on line 171
[10:35:27] WARNING: no name column found on line 172
[10:35:27] WARNING: no name column found on line 173
[10:35:27] WARNING: no name column found on line 174
[10:35:27] WARNING: no name column found on line 175
[10:35:27] WARNING: no name column found on line 176
[10:35:27] WARNING: no name column found on line 177
[10:35:27] WARNING: no name column found on line 178
[10:35:27] WARNING: no name column found on line 179
[10:35:27] WARNING: no name column found on line 180
[10:35:27] WARNING: no name column found on line 181
[10:35:27] WARNING: no name column found on line 182
[10:35:27] WARNING: no name column found on line 183
[10:35:27] WARNING: no name column found on line 184
[10:35:27] WARNING: no name column found on line 185
[10:35:27] WARNING: no name column found on line 186
[10:35:27] WARNING: no name column found on line 187
[10:35:27] WARNING: no name column found on line 188
[10:35:27] WARNING: no name column found on line 189
[10:35:27] WARNING: no name column found on line 190
[10:35:27] WARNING: no name column found on line 191
[10:35:27] WARNING: no name column found on line 192
[10:35:27] WARNING: no name column found on line 193
[10:35:27] WARNING: no name column found on line 194
[10:35:27] WARNING: no name column found on line 195
[10:35:27] WARNING: no name column found on line 196
[10:35:27] WARNING: no name column found on line 197
[10:35:27] WARNING: no name column found on line 198
[10:35:27] WARNING: no name column found on line 199
[10:35:27] WARNING: no name column found on line 200
[10:35:27] WARNING: no name column found on line 201
[10:35:27] WARNING: no name column found on line 202
[10:35:27] WARNING: no name column found on line 203
[10:35:27] WARNING: no name column found on line 204
[10:35:27] WARNING: no name column found on line 205
[10:35:27] WARNING: no name column found on line 206
[10:35:27] WARNING: no name column found on line 207
[10:35:27] WARNING: no name column found on line 208
[10:35:27] WARNING: no name column found on line 209
[10:35:27] WARNING: no name column found on line 210
[10:35:27] WARNING: no name column found on line 211
[10:35:27] WARNING: no name column found on line 212
[10:35:27] WARNING: no name column found on line 213
[10:35:27] WARNING: no name column found on line 214
[10:35:27] WARNING: no name column found on line 215
[10:35:27] WARNING: no name column found on line 216
......
----------------------------------------------------------------------
Ran 9 tests in 0.119s

OK
..................
----------------------------------------------------------------------
Ran 18 tests in 0.643s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.082s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 0.027s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.020s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.016s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.048s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 0.001s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.003s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.003s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.016s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.021s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 2.460s

OK
..........
----------------------------------------------------------------------
Ran 10 tests in 0.049s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
..........
----------------------------------------------------------------------
Ran 10 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.054s

OK
.....................
----------------------------------------------------------------------
Ran 21 tests in 2.873s

OK
mol_197
217.95,36.15,110.32,11.58,109.64,11.08,90.35,2.95,0.00
mol_223
250.23,6.99,134.50,1.36,134.43,1.36,85.51,0.66,0.00
mol_269
216.09,5.31,104.07,0.38,102.88,0.40,88.34,0.45,6.00
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...[10:35:40] 

****
Pre-condition Violation
molecule has no conformers
Violation occurred on line 37 in file /Users/jinserk/kyu-dev/rdkit/Code/GraphMol/MolChemicalFeatures/MolChemicalFeature.cpp
Failed Expression: dp_mol->getNumConformers()
****

.
----------------------------------------------------------------------
Ran 4 tests in 0.024s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 3.640s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.101s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.014s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.022s
OK
.....[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
[10:35:45] WARNING: not removing hydrogen atom without neighbors
.....
----------------------------------------------------------------------
Ran 10 tests in 0.315s

OK
ssssss.....s.....
----------------------------------------------------------------------
Ran 17 tests in 0.152s

OK (skipped=7)
s
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (skipped=1)
..........
----------------------------------------------------------------------
Ran 10 tests in 0.579s

OK
..[10:35:48] SMARTS Parse Error: syntax error while parsing: boromicacid
[10:35:48] SMARTS Parse Error: Failed parsing SMARTS 'boromicacid' for input: 'boromicacid'
[10:35:48] SMARTS Parse Error: syntax error while parsing: carboxylicacid,acidchlroide
[10:35:48] SMARTS Parse Error: Failed parsing SMARTS 'carboxylicacid,acidchlroide' for input: 'carboxylicacid,acidchlroide'
[10:35:48] SMARTS Parse Error: syntax error while parsing: carboxyliccaid,acidchloride
[10:35:48] SMARTS Parse Error: Failed parsing SMARTS 'carboxyliccaid,acidchloride' for input: 'carboxyliccaid,acidchloride'
[10:35:48] reaction has no reactants
[10:35:48] reaction has no products
[10:35:48] initialization failed
[10:35:48] reaction has no reactants
[10:35:48] reaction has no products
.
----------------------------------------------------------------------
Ran 3 tests in 0.023s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.012s

OK
................[10:35:49] ERROR: 
[10:35:49] ERROR: 
.
----------------------------------------------------------------------
Ran 17 tests in 0.033s

OK
!!! TEST FAILURE:  python UnitTestMol3D.py {}
!!! TEST FAILURE:  python UnitTestDocTestsChem.py {}
<end of output>
Test time =  90.02 sec
----------------------------------------------------------
Test Failed.
"pythonTestDirChem" end time: Nov 01 10:36 EDT
"pythonTestDirChem" time elapsed: 00:01:30
----------------------------------------------------------

End testing: Nov 01 10:36 EDT
```

```
Your code sample here
```

**Comment by greglandrum** [comment]
Finally managed to get python 3.8 built and working on my machine and I can confirm the problem.
The reason this only occurs in python 3.8 seems to be that the tests in `UnitTestDocTestsChem.py` aren't actually being run in python 3.6 and 3.7, so we just weren't noticing the test failure.

**Comment by greglandrum** [comment]
Note that the failure is due to the expected test results in the doctest being wrong, not the underlying RDKit code itself.
