### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by intrigus-lgtm** [rdkit/rdkit#3139]
~~The build for #3128 is [failing](https://dev.azure.com/rdkit-org/RDKit-main-build/_build/results?buildId=1178&view=logs&j=d42b4615-9c42-5e39-433b-1455f2661188&t=252d3907-1082-5b31-96c1-a55ede2a1791&l=63) due to a memory leak.~~

**Configuration:**

- RDKit Version: master, 39bcee635e0ee8bc5da6798318fdcd4602c4baa6
- Operating system: Linux
- Are you using conda? No
- If you are not using conda: how did you install the RDKit? Self-built using Cmake

**Description:**

Either build https://github.com/rdkit/rdkit/pull/3128 or use the binary I provide here:
[smiles_string_to_mol_fuzzer.txt](https://github.com/rdkit/rdkit/files/4577096/smiles_string_to_mol_fuzzer.txt)
**Remove the extension/`chmod +x` it**
You can also just compile https://github.com/rdkit/rdkit/blob/44d47ef1a2ef65922945756b71f4395c0973841e/Code/Fuzz/smiles_string_to_mol_fuzzer.cc using `-fsanitize=address`.

The input that is being used for the program is ~~`COc(c1)cccc1C#N`~~ `COc(c1)cccc1C#`

Run this command
```
./rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer ./rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer/300e696782d50f5a92a02dbb37b1e14b33bb7bfb
```

```
Running: ./rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer/300e696782d50f5a92a02dbb37b1e14b33bb7bfb

=================================================================
==7418==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 160 byte(s) in 2 object(s) allocated from:
    #0 0x572862 in operator new(unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x572862)
    #1 0x73be9f in RDKit::RWMol::createPartialBond(unsigned int, RDKit::Bond::BondType) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/RWMol.cpp:444:13
    #2 0x63f1e5 in yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) /home/sg/dev/google-rewards/rdkit/build/Code/GraphMol/SmilesParse/smiles.yy:215:20
    #3 0x585941 in RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:112:11
    #4 0x57d70e in RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:149:10
    #5 0x576d4c in RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:215:5
    #6 0x57a789 in RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:363:9
    #7 0x575d8e in SmilesToMol /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:79:10
    #8 0x575d8e in LLVMFuzzerTestOneInput /home/sg/dev/google-rewards/rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer.cc:30
    #9 0x47d66a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x47d66a)
    #10 0x46ffac in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x46ffac)
    #11 0x475431 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x475431)
    #12 0x497a52 in main (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x497a52)
    #13 0x7fd4c669909a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x572862 in operator new(unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x572862)
    #1 0x59b15b in allocate /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h:111:27
    #2 0x59b15b in allocate /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h:436
    #3 0x59b15b in _M_allocate /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:296
    #4 0x59b15b in void std::vector<RDKit::Dict::Pair, std::allocator<RDKit::Dict::Pair> >::_M_realloc_insert<RDKit::Dict::Pair>(__gnu_cxx::__normal_iterator<RDKit::Dict::Pair*, std::vector<RDKit::Dict::Pair, std::allocator<RDKit::Dict::Pair> > >, RDKit::Dict::Pair&&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc:427
    #5 0x5fccb6 in emplace_back<RDKit::Dict::Pair> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc:109:4
    #6 0x5fccb6 in push_back /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:1091
    #7 0x5fccb6 in void RDKit::Dict::setPODVal<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:259
    #8 0x63f668 in setVal /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:268:51
    #9 0x63f668 in setProp<int> /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/RDProps.h:81
    #10 0x63f668 in yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) /home/sg/dev/google-rewards/rdkit/build/Code/GraphMol/SmilesParse/smiles.yy:218
    #11 0x585941 in RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:112:11
    #12 0x57d70e in RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:149:10
    #13 0x576d4c in RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:215:5
    #14 0x57a789 in RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:363:9
    #15 0x575d8e in SmilesToMol /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:79:10
    #16 0x575d8e in LLVMFuzzerTestOneInput /home/sg/dev/google-rewards/rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer.cc:30
    #17 0x47d66a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x47d66a)
    #18 0x46ffac in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x46ffac)
    #19 0x475431 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x475431)
    #20 0x497a52 in main (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x497a52)
    #21 0x7fd4c669909a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 36 byte(s) in 2 object(s) allocated from:
    #0 0x572862 in operator new(unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x572862)
    #1 0x5fc73e in _M_construct<char *> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.tcc:219:14
    #2 0x5fc73e in _M_construct_aux<char *> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:236
    #3 0x5fc73e in _M_construct<char *> /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:255
    #4 0x5fc73e in basic_string /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/basic_string.h:440
    #5 0x5fc73e in void RDKit::Dict::setPODVal<int>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:259
    #6 0x63f668 in setVal /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/Dict.h:268:51
    #7 0x63f668 in setProp<int> /home/sg/dev/google-rewards/rdkit/Code/RDGeneral/RDProps.h:81
    #8 0x63f668 in yysmiles_parse(char const*, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >*, RDKit::Atom*&, RDKit::Bond*&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >*, void*, int&) /home/sg/dev/google-rewards/rdkit/build/Code/GraphMol/SmilesParse/smiles.yy:218
    #9 0x585941 in RDKit::(anonymous namespace)::smiles_parse_helper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&, RDKit::Atom*&, RDKit::Bond*&, int) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:112:11
    #10 0x57d70e in RDKit::(anonymous namespace)::smiles_parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:149:10
    #11 0x576d4c in RDKit::toMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<RDKit::RWMol*, std::allocator<RDKit::RWMol*> >&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:215:5
    #12 0x57a789 in RDKit::SmilesToMol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, RDKit::SmilesParserParams const&) /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:363:9
    #13 0x575d8e in SmilesToMol /home/sg/dev/google-rewards/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:79:10
    #14 0x575d8e in LLVMFuzzerTestOneInput /home/sg/dev/google-rewards/rdkit/Code/Fuzz/smiles_string_to_mol_fuzzer.cc:30
    #15 0x47d66a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x47d66a)
    #16 0x46ffac in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x46ffac)
    #17 0x475431 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x475431)
    #18 0x497a52 in main (/home/sg/dev/google-rewards/rdkit/build/Code/Fuzz/smiles_string_to_mol_fuzzer+0x497a52)
    #19 0x7fd4c669909a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 292 byte(s) leaked in 6 allocation(s).
```

**Comment by intrigus-lgtm** [comment]
Sorry, I made a mistake, the offending smiles formula is actually `COc(c1)cccc1C#` and **not** `COc(c1)cccc1C#N`.
Notice that this is likely an invalid smiles formula.

**Comment by bp-kelley** [comment]
@intrigus-lgtm I'm testing a fix for this, it may be ready tomorrow, certainly by Friday.

**Comment by intrigus-lgtm** [comment]
@bp-kelley Great news.
But there is no need to rush anymore, since no prs are blocked by this anymore :)
