### ISSUE TITLE
Some Stereoisomers Enumeration tests fail w/ python 3.8.2 + GCC 10.1.1

### ISSUE THREAD

**Issue by rvianello** [rdkit/rdkit#3185]
**Configuration:**

- RDKit Version: current tip of the master branch
- Operating system: Linux (dockerized Fedora 32)
- Python version (if relevant): 3.8.2
- Are you using conda? no

**Description:**

Following a successful C++ and python build, two test cases from `pythonTestDirChem` are observed to fail: 

```
======================================================================
FAIL: testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnitTestMol3D.py", line 218, in testEnumerateStereoisomersRandomSamplingShouldBeDeterministicAndPortable
    self.assertEqual(smiles, expected)
AssertionError: Items in the first set but not the second:
'C/C(F)=C/[C@@H](Cl)/C=C(\\Br)[C@H](N)I'
'C/C(F)=C\\[C@H](Cl)/C=C(\\Br)[C@H](N)I'
Items in the second set but not the first:
'C/C(F)=C/[C@@H](Cl)/C=C(/Br)[C@@H](N)I'
'C/C(F)=C/[C@H](Cl)/C=C(\\Br)[C@H](N)I'

----------------------------------------------------------------------

======================================================================
FAIL: EnumerateStereoisomers (rdkit.Chem.EnumerateStereoisomers)
Doctest: rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.8/doctest.py", line 2204, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
  File "/workspaces/rdkit-cpp-devel/rdkit/rdkit/Chem/EnumerateStereoisomers.py", line 164, in EnumerateStereoisomers

----------------------------------------------------------------------
File "/workspaces/rdkit-cpp-devel/rdkit/rdkit/Chem/EnumerateStereoisomers.py", line 286, in rdkit.Chem.EnumerateStereoisomers.EnumerateStereoisomers
Failed example:
    for smi in sorted(Chem.MolToSmiles(x, isomericSmiles=True) for x in isomers):
        print(smi)
Expected:
    F[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)Br
    F[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)Br
    F[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)Br
Got:
    F[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)Br
    F[C@@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)Br
    F[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@@H](Cl)[C@H](Cl)[C@@H](Cl)[C@H](Cl)[C@H](Cl)Br


----------------------------------------------------------------------```

FWIW, all tests pass if an identically configured build is performed in a container based on Fedora 31 (python 3.7.7 + GCC 9.3.1). boost version is 1.69.0 for both distros.

I'll try and investigate the cause, and post further details.

<!-- If you have a support question, please use the rdkit-discuss mailing list: 
https://sourceforge.net/p/rdkit/mailman/ -->

**Comment by Darkless012** [comment]
I'm having the same issue on Python 3.8.2. Thanks for report.
How do you run tests? 
- `ctest  --output-on-failure` or
- `make test` which will run `ctest` eventually

**Comment by Darkless012** [comment]
duplicate of: https://github.com/rdkit/rdkit/issues/2757
