### ISSUE TITLE
Segfault when parsing InChI for Pubchem compound

### ISSUE THREAD

**Issue by YuanyueLi** [rdkit/rdkit#3192]
**Configuration:**

- RDKit Version: '2020.03.2' or '2020.03.1'
- Operating system: Linux
- Python version (if relevant): 3.7.6
- Are you using conda? Yes
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?

**Description:**

I got Segmentation fault output when I run the code below

```
from rdkit import Chem
Chem.MolFromInchi('InChI=1S/C5H14O3SSi/c1-5-9(10,6-2,7-3)8-4/h5H2,1-4H3')
```

**Comment by bp-kelley** [comment]
This looks like an rdkit exception to me, not a segmentation fault, but the index below looks odd to me.  @greglandrum, this might be work a look

```
>>> from rdkit import Chem
>>> Chem.MolFromInchi('InChI=1S/C5H14O3SSi/c1-5-9(10,6-2,7-3)8-4/h5H2,1-4H3')
[08:37:35] 

****
Range Error
idx1
Violation occurred on line 319 in file /Users/glandrum/anaconda3/conda-bld/rdkit_1585463137433/work/Code/GraphMol/ROMol.cpp
Failed Expression: 3679572512 < 10
****

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bkelley/anaconda3/lib/python3.7/site-packages/rdkit/Chem/inchi.py", line 71, in MolFromInchi
    mol, retcode, message, log = rdinchi.InchiToMol(inchi, sanitize, removeHs)
RuntimeError: Range Error
	idx1
	Violation occurred on line 319 in file Code/GraphMol/ROMol.cpp
	Failed Expression: 3679572512 < 10
	RDKIT: 2020.03.1
	BOOST: 1_67
```

Could you paste your output?

**Comment by YuanyueLi** [comment]
I use the latest version of miniconda, then install rdkit with the following command:
`conda install rdkit`
And run the command above, I only got "Segmentation fault" output (see the picture below)
![image](https://user-images.githubusercontent.com/6198768/83190430-4395c600-a0e7-11ea-8714-26c40cf230e2.png)

**Comment by YuanyueLi** [comment]
By the way, this molecule can be found in pubchem:

https://pubchem.ncbi.nlm.nih.gov/compound/145829290

It's a real molecule. How to make rdkit parse it?

**Comment by greglandrum** [comment]
I can reproduce the seg fault. This is clearly a bug in our InChI parser.
If you want to work with this molecule, or any other, from Pubchem, I would strongly recommend that you use the SMILES that PubChem makes available instead of the InChI.
Though it is possible to reconstruct a molecule from InChI, the format is *not* designed for that, so the molecules you get are often a bit "strange" relative to what the input structure was.
SMILES is designed for structural interchange

**Comment by YuanyueLi** [comment]
OK, thanks for the suggestion. Also, thanks for developing and maintaining the wonderful rdkit software!

**Comment by greglandrum** [comment]
the robot is closing any issue that has not been touched for a long time. If someone things it's important and is either willing to work on an issue or find someone else to do it, the status can always been changed from "wont fix" to "fixed" :-)

**Comment by YuanyueLi** [comment]
Hi, I have retested this molecule using the latest version of RDKit. The InChI no longer causes a crash; however, RDKit still can't parse this molecular InChI. Please see the details below:

- RDKit Version: '2024.09.3'
- Operating system: Linux
- Python version (if relevant): 3.12.7
- Are you using conda? I use mamba
- If you are using conda, which channel did you install the rdkit from? conda-forge
- If you are not using conda: how did you install the RDKit?
  - mamba create -c conda-forge -n my-rdkit-env rdkit=2024.09.3 python=3.12 -y -q

```bash
mamba create -c conda-forge -n my-rdkit-env rdkit=2024.09.3 python=3.12 -y -q && mamba activate my-rdkit-env && python
```

```python
from rdkit import Chem
mol=Chem.MolFromSmiles('CCS(=[Si])(OC)(OC)OC')
print("InChI:", inchi:=Chem.MolToInchi(mol))
Chem.MolFromInchi(inchi)
```

![image](https://github.com/user-attachments/assets/cc51427a-dcac-481f-8d2f-e37a502702a1)

**Comment by bp-kelley** [comment]
Inchi is adding a triple bond which feels  wrong IMO

```
>>> m2 = Chem.MolFromInchi(inchi, sanitize=False)
>>> Chem.MolToSmiles(m2)
'CC[S-](#[Si+])(OC)(OC)OC'
```

Inchi is telling you there's an error btw:  [13:04:53] WARNING: Accepted unusual valence(s): Si(2)

**Comment by bp-kelley** [comment]
I think you might want to treat warnings as errors

```
>>> help(Chem.MolToInchi)
MolToInchi(mol, options='', logLevel=None, treatWarningAsError=False)
    Returns the standard InChI string for a molecule
    
    Keyword arguments:
    logLevel -- the log level used for logging logs and messages from InChI
    API. set to None to diable the logging completely
    treatWarningAsError -- set to True to raise an exception in case of a
    molecule that generates warning in calling InChI API. The resultant InChI
    string and AuxInfo string as well as the error message are encoded in the
    exception.
```

**Comment by bp-kelley** [comment]
It's unclear where this is happening

```
>>> m = Chem.MolFromSmiles("S=[Si]")
>>> Chem.MolToInchi(m)
[19:15:12] WARNING: Accepted unusual valence(s): Si(2)

'InChI=1S/SSi/c1-2'
```

This inchi is correct for S=[Si]:
https://en.wikipedia.org/wiki/Silicon_monosulfide

but when we read it back in:

```
>>> Chem.MolToSmiles(Chem.MolFromInchi(inchi))
'[Si-]#[S+]'
```

**Comment by greglandrum** [comment]
The problem here is that `S=[Si]` is a radical (as is the original molecule) and InChI doesn't handle radicals correctly. The warning is telling you this (as usual, it's often not a good idea to ignore warnings).

Here's a simple demonstration of this:
```
In [13]: Chem.MolToInchi(Chem.MolFromSmiles('[C]-[C]'))
[15:23:21] WARNING: Accepted unusual valence(s): C(1)

Out[13]: 'InChI=1S/C2/c1-2'

In [14]: Chem.MolToInchi(Chem.MolFromSmiles('[C]=[C]'))
[15:23:25] WARNING: Accepted unusual valence(s): C(2)

Out[14]: 'InChI=1S/C2/c1-2'

In [15]: Chem.MolToInchi(Chem.MolFromSmiles('[C]#[C]'))
[15:23:30] WARNING: Accepted unusual valence(s): C(3)

Out[15]: 'InChI=1S/C2/c1-2'
```

The RDKit should probably still not fail with the `S=[Si]` InChI, but it's not going to produce anything correct
