### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by danielfllaneza** [rdkit/rdkit#3215]
I have activated my environment and it contains rdkit:
```
conda activate dalkeCourse
conda list
```
which indicates that I have installed rdkit:
```
rdkit                     2018.09.1       py37h4a7b924_1000    conda-forge
```
However, upon running a .py file in my command line I get the following error:
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from model import *
  File "/../../../PythonNotebooks/model/__init__.py", line 1, in <module>
    from .baseline_models import *
  File "/../../../PythonNotebooks/model/baseline_models.py", line 17, in <module>
    from rdkit import Chem
ModuleNotFoundError: No module named 'rdkit'
```

**Comment by danielfllaneza** [comment]
Thanks for your reply. I am running the .py file in the same shell as per the following capture:
![rdkit](https://user-images.githubusercontent.com/44854593/84018535-6db97480-a980-11ea-98be-a5892e11d985.PNG)

model is a package with an __init__.py file and the corresponding modules (amongst which .baseline_models.py which imports rdkit). The __init__.py file imports the different modules at the start:
```
from .baseline_models import *
etc.
```
By running the main.py file I call a specific module within the model package. Let me know if you need more information.

**Comment by ZihaoWang1995** [comment]
I was troubled by this problem serveral times, however, I didn't get a effective way to deal with it.
Sometimes, removing it and install a newer version of rdkit, can solve it.
I'm not sure it is really useful. Just for your reference.

**Comment by danielfllaneza** [comment]
Thanks for your suggestion @ZihaoWang1995. It seems to be working today, I don't understand why since the commands used are the same.

**Comment by ZihaoWang1995** [comment]
Strange... Fortunately, it works.
Anyway, best wishes! @danielfllaneza

**Comment by danielfllaneza** [comment]
Well it does not work again anymore... not sure what's going on

**Comment by greglandrum** [comment]
At this point I'm kind of guessing. Could it be that something in the `model` package either messes around with `sys.path` or spawns a new python process?
