### ISSUE TITLE
ImportError: cannot import name 'Chem' from 'rdkit'

### ISSUE THREAD

**Issue by hrvanderlingen** [rdkit/rdkit#3248]
**Configuration:**
- RDKit Version: rdkit-2020.03.3.0
- Operating system: MacOS Catalina. 10.15.4.
- Python version (if relevant): 3.7.7
- Are you using conda? yes
- If you are using conda, which channel did you install the rdkit from?  https://repo.anaconda.com/archive/Anaconda3-2020.02-MacOSX-x86_64.sh
conda install -c rdkit rdkit

**Description:**

rdkit works perfectly fine on de command line but I am unable to get an executable file to run.  The python file has just one line:

from rdkit import Chem 

See Visual Studio output:

source activate ~/anaconda3/envs/my-rdkit-env
~/anaconda3/envs/my-rdkit-env/bin/python ~/Documents/projects/python/rdtest.py
 python % ~/anaconda3/envs/my-rdkit-env/bin/python ~/Documents/projects/python/rdtest.py
Traceback (most recent call last):
  File "~/Documents/projects/python/rdtest.py", line 1, in <module>
    from rdkit import Chem 
  File "~/Documents/projects/python/rdkit.py", line 3, in <module>
    from rdkit import Chem
ImportError: cannot import name 'Chem' from 'rdkit' (~/Documents/projects/python/rdkit.py)
(my-rdkit-env) python % 

(manually placed the tildes)

**Comment by hrvanderlingen** [comment]
Solved it: my working directory contained a file called rdkit.py. Messed things up.
