### ISSUE TITLE
SVG export - Python 3 support

### ISSUE THREAD

**Issue by maddogcz** [rdkit/rdkit#398]
Hi,

I've found a possible error in rdkit python bindings (for python 3), when I want to draw mol to SVG - import from current folder is wrongly used in rdkit.sping SVG and PDF package. I also found loads of outdated unsupported stuff like cStringIO import, .has_key() dict method or using string module functions (lower, split etc.) instead of string object methods.

This should reproduce the error:

```python
from rdkit import Chem
from rdkit.Chem import Draw

mol = Chem.MolFromSmiles("CCC")
Draw.MolToFile(mol, "/tmp/mol.svg")
```

**Comment by jranke** [comment]
Any news on this? I checked building 2015_03_01 and current HEAD against Python 3.4 and always get the bug, *i.e.* cannot export to ps or svg:
 
```
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> from rdkit.Chem import Draw
>>> mol = Chem.MolFromSmiles("CCCCO")
>>> Draw.MolToFile(mol, "test.ps")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/__init__.py", line 167, in MolToFile
    canvas = Canvas(size=size,name=fileName,imageType=imageType)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/spingCanvas.py", line 31, in __init__
    from rdkit.sping.PS.pidPS import PSCanvas as _Canvas  #@UnresolvedImport
  File "/home/jranke/git/rdkit/rdkit/sping/PS/__init__.py", line 2, in <module>
    from pidPS import *
ImportError: No module named 'pidPS'
>>> Draw.MolToFile(mol, "test.svg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/__init__.py", line 167, in MolToFile
    canvas = Canvas(size=size,name=fileName,imageType=imageType)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/spingCanvas.py", line 33, in __init__
    from rdkit.sping.SVG.pidSVG import SVGCanvas as _Canvas
  File "/home/jranke/git/rdkit/rdkit/sping/SVG/__init__.py", line 3, in <module>
    from pidSVG import *
ImportError: No module named 'pidSVG'
```

**Comment by giallu** [comment]
Not a proper fix but maybe you can avoid the issue by activating the cairo
backend (e.g. no sping involved). You can do it by running cmake with the
-D RDK_BUILD_CAIRO_SUPPORT:BOOL=ON option.

On Fri, Oct 2, 2015 at 9:12 AM, Johannes Ranke <notifications@github.com>
wrote:

> Any news on this? I checked building 2015_03_01 and current HEAD against
> Python 3.4 and always get the bug, *i.e.* cannot export to ps or svg:
>
> Python 3.4.2 (default, Oct  8 2014, 10:45:20)
> [GCC 4.9.1] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from rdkit import Chem
> >>> from rdkit.Chem import Draw
> >>> mol = Chem.MolFromSmiles("CCCCO")
> >>> Draw.MolToFile(mol, "test.ps")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/jranke/git/rdkit/rdkit/Chem/Draw/__init__.py", line 167, in MolToFile
>     canvas = Canvas(size=size,name=fileName,imageType=imageType)
>   File "/home/jranke/git/rdkit/rdkit/Chem/Draw/spingCanvas.py", line 31, in __init__
>     from rdkit.sping.PS.pidPS import PSCanvas as _Canvas  #@UnresolvedImport
>   File "/home/jranke/git/rdkit/rdkit/sping/PS/__init__.py", line 2, in <module>
>     from pidPS import *
> ImportError: No module named 'pidPS'
> >>> Draw.MolToFile(mol, "test.svg")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/jranke/git/rdkit/rdkit/Chem/Draw/__init__.py", line 167, in MolToFile
>     canvas = Canvas(size=size,name=fileName,imageType=imageType)
>   File "/home/jranke/git/rdkit/rdkit/Chem/Draw/spingCanvas.py", line 33, in __init__
>     from rdkit.sping.SVG.pidSVG import SVGCanvas as _Canvas
>   File "/home/jranke/git/rdkit/rdkit/sping/SVG/__init__.py", line 3, in <module>
>     from pidSVG import *
> ImportError: No module named 'pidSVG'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdkit/rdkit/issues/398#issuecomment-144940730>.
>



-- 
Gianluca Sforna

http://morefedora.blogspot.com
http://plus.google.com/+gianlucasforna - http://twitter.com/giallu

**Comment by jranke** [comment]
Thanks for the hint - but I get the exact same result when activating the cairo backend like this...

**Comment by greglandrum** [comment]
You can do either SVG or PNG (PNG only with the cairo backend) using the new MolDraw2D functionality.
There's some information here: http://rdkit.blogspot.com/2015/02/new-drawing-code.html

**Comment by jranke** [comment]
Thanks for the hint - however I am using postscript, because I can import this in R using grImport. Not a big deal at the moment, as using python 2.7 is fine for now.

**Comment by jranke** [comment]
@bp-kelley 
I still get errors with current HEAD and python3.4:
```py
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> from rdkit.Chem import Draw
>>> mol = Chem.MolFromSmiles("CCCCO")
```

For SVG:

```py
>>> Draw.MolToFile(mol, "/tmp/mol.svg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/__init__.py", line 170, in MolToFile
    drawer = MolDrawing(canvas=canvas, drawingOptions=options)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/MolDrawing.py", line 105, in __init__
    fill=True, stroke=False)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/spingCanvas.py", line 89, in addCanvasPolygon
    closed=1)
  File "/home/jranke/git/rdkit/rdkit/sping/SVG/pidSVG.py", line 317, in drawPolygon
    pointStr = _PointListToSVG(pointlist, dupFirst=closed)
  File "/home/jranke/git/rdkit/rdkit/sping/SVG/pidSVG.py", line 77, in _PointListToSVG
    for i in xrange(len(points)):
NameError: name 'xrange' is not defined
```

and for PostScript:

```py
>>> Draw.MolToFile(mol, "/tmp/test.ps")
Traceback (most recent call last):
  File "/home/jranke/git/rdkit/rdkit/sping/PS/psmetrics.py", line 225, in stringwidth
    widths = _Widths[encoding][string.lower(font)]
AttributeError: 'module' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/__init__.py", line 180, in MolToFile
    drawer.AddMol(mol, **kwargs)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/MolDrawing.py", line 553, in AddMol
    labelSize = self._drawLabel(symbol, pos, baseOffset, font, color=color, orientation=orient)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/MolDrawing.py", line 354, in _drawLabel
    labelSize = self.canvas.addCanvasText(label, (x1, y1, baseOffset), font, color, **kwargs)
  File "/home/jranke/git/rdkit/rdkit/Chem/Draw/spingCanvas.py", line 64, in addCanvasText
    txtWidth, txtHeight = self.canvas.stringBox(text, font)
  File "/home/jranke/git/rdkit/rdkit/sping/pid.py", line 288, in stringBox
    return self.stringWidth(s, font), self.fontHeight(font)
  File "/home/jranke/git/rdkit/rdkit/sping/PS/pidPS.py", line 494, in stringWidth
    self.fontMapEncoding["EncodingName"]) * font.size * 0.001
  File "/home/jranke/git/rdkit/rdkit/sping/PS/psmetrics.py", line 227, in stringwidth
    raise KeyError("Improper encoding {0} or font name {1}".format(encoding, font))
KeyError: 'Improper encoding Latin1Encoding or font name Helvetica'
```
