### ISSUE TITLE
rdkit.Chem.Draw.MolToImage

### ISSUE THREAD

**Issue by DachsiRosi** [rdkit/rdkit#4045]
Hi,
I'm currently trying to rewrite my App for MacOs which I have coded for Windows.

I print Images of molecules in to my Tkinter Window on Window using this piece of code:
load = rdkit.Chem.Draw.MolToImage(mol, size=(400, 400))
render = ImageTk.PhotoImage(load)
imgkj = Label(Frame4, image=render)
imgkj.image = render
imgkj.place( x=850, y=50)  

_But apparently this doesn't work for MacOs because I get the following error:

Exception in Tkinter callback
_Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/opt/anaconda3/lib/python3.8/site-packages/tkmacosx/basewidgets/button_base.py", line 874, in cmd
    self.cnf['command']()
  File "/Applications/NameofFolder/NameofCode.py", line 6451, in smiles
    load = rdkit.Chem.Draw.MolToImage(mol, size=(400, 400))
  File "/opt/anaconda3/lib/python3.8/site-packages/rdkit/Chem/Draw/__init__.py", line 101, in MolToImage
    img, canvas = _createCanvas(size)
  File "/opt/anaconda3/lib/python3.8/site-packages/rdkit/Chem/Draw/__init__.py", line 56, in _createCanvas
    canvas = Canvas(img)
  File "/opt/anaconda3/lib/python3.8/site-packages/rdkit/Chem/Dra_w/cairoCanvas.py", line 147, in __init__
    imgd = getattr(image, 'tobytes', image.tostring)("raw", "BGRA")
AttributeError: 'Image' object has no attribute 'tostring'_

I've tried to print it to a canvas, which isn't working either.
What can I do to make it work on MacOs?
Thank you in advance.

Best wishes

**Comment by greglandrum** [comment]
The issue template asks you a series of questions that make it easier for us to help.
The fact that you've either deleted those or only answered a subset of them makes it more difficult for us to help, so I'm closing this issue.

Please feel free to edit the issue description to include the requested information and reopen the issue and then we'll try to help.
