### ISSUE TITLE
Requesting "density" fingerprint Hydrogen molecule fails with exception

### ISSUE THREAD

**Issue by ricrogz** [rdkit/rdkit#4567]
Calculating a "density" fingerprint on a H2 molecule fails due to a "Divide by zero" exception:

```python
# morgan_test.py
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors
mol = AllChem.MolFromSmiles('[HH]')
fp1 = Descriptors.FpDensityMorgan1(mol)
print(fp1)
```

```
$ morgan_test.py
--
[10:11:27] WARNING: not removing hydrogen atom without neighbors
Traceback (most recent call last):
  File "./morgan_test.py", line 4, in <module>
    fp1 = Descriptors.FpDensityMorgan1(mol)
  File "/rdkit/lib/python3.8/site-packages/rdkit/Chem/Descriptors.py", line 208, in FpDensityMorgan1
    return _FingerprintDensity(x, _rdMolDescriptors.GetMorganFingerprint, 1)
  File "/rdkit/lib/python3.8/site-packages/rdkit/Chem/Descriptors.py", line 204, in _FingerprintDensity
    return float(val) / mol.GetNumHeavyAtoms()
ZeroDivisionError: float division by zero
```

This, of course, is because there are no heavy atoms in this mol. I'm not sure, though what should be returned here: 0? `float(val)`? or something different?

**Comment by greglandrum** [comment]
Yeah, I think it’s Zero

**Comment by ricrogz** [comment]
Ok, I'll submit a PR.
