### ISSUE TITLE
Dockerfile is not working in Code/Minimallib/docker

### ISSUE THREAD

**Issue by seongsangcho-hits** [rdkit/rdkit#4773]
-----------------------------------------

I tried to build using `npm run build` operation.

but it was not working.

here is error message

-----------------------------------------

```
Building distribution files for release master
[+] Building 67.9s (13/28)                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 2.74kB                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 2B                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/debian:buster                                                                             0.0s
 => CACHED [build-stage  1/23] FROM docker.io/library/debian:buster                                                                          0.0s
 => [build-stage  2/23] RUN apt-get update && apt-get upgrade -y && apt install -y   curl   wget   cmake   python3   g++   libeigen3-dev    17.2s
 => [build-stage  3/23] WORKDIR /opt                                                                                                         0.0s
 => [build-stage  4/23] RUN wget -q https://boostorg.jfrog.io/artifactory/main/release/1.67.0/source/boost_1_67_0.tar.gz &&   tar xzf boos  22.7s
 => [build-stage  5/23] WORKDIR /opt/boost_1_67_0                                                                                            0.0s
 => [build-stage  6/23] RUN ./bootstrap.sh --prefix=/opt/boost --with-libraries=system &&   ./b2 install                                    25.7s
 => [build-stage  7/23] WORKDIR /opt                                                                                                         0.0s
 => [build-stage  8/23] RUN git clone https://github.com/emscripten-core/emsdk.git                                                           1.7s
 => [build-stage  9/23] WORKDIR /opt/emsdk                                                                                                   0.0s
 => ERROR [build-stage 10/23] RUN ./emsdk update-tags &&   ./emsdk install latest &&   ./emsdk activate latest                               0.4s
------
 > [build-stage 10/23] RUN ./emsdk update-tags &&   ./emsdk install latest &&   ./emsdk activate latest:
#13 0.338 `update-tags` is not longer needed.  To install the latest tot release just run `install tot`
#13 0.403 error: tool or SDK not found: 'sdk-releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'
#13 0.403 Resolving SDK alias 'latest' to '3.0.0'
#13 0.403 Resolving SDK version '3.0.0' to 'sdk-releases-upstream-7fbe748230f2ce99abbf975d9ad997699efb3153-64bit'
------
executor failed running [/bin/sh -c ./emsdk update-tags &&   ./emsdk install latest &&   ./emsdk activate latest]: exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rdkit/rdkit@1.0.0 build: `bash Code/MinimalLib/scripts/build_rdkitjs.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @rdkit/rdkit@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/css/.npm/_logs/2021-12-07T07_08_19_988Z-debug.log
```

**/2021-12-07T07_08_19_988Z-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @rdkit/rdkit@1.0.0~prebuild: @rdkit/rdkit@1.0.0
6 info lifecycle @rdkit/rdkit@1.0.0~build: @rdkit/rdkit@1.0.0
7 verbose lifecycle @rdkit/rdkit@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle @rdkit/rdkit@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/css/rdkit/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/css/Desktop/library/emsdk:/Users/css/Desktop/library/emsdk/upstream/emscripten:/Users/css/Desktop/library/emsdk/node/14.15.5_64bit/bin:/opt/homebrew/bin:/opt/homebrew/sbin
9 verbose lifecycle @rdkit/rdkit@1.0.0~build: CWD: /Users/css/rdkit
10 silly lifecycle @rdkit/rdkit@1.0.0~build: Args: [ '-c', 'bash Code/MinimalLib/scripts/build_rdkitjs.sh' ]
11 silly lifecycle @rdkit/rdkit@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle @rdkit/rdkit@1.0.0~build: Failed to exec build script
13 verbose stack Error: @rdkit/rdkit@1.0.0 build: `bash Code/MinimalLib/scripts/build_rdkitjs.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid @rdkit/rdkit@1.0.0
15 verbose cwd /Users/css/rdkit
16 verbose Darwin 20.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error @rdkit/rdkit@1.0.0 build: `bash Code/MinimalLib/scripts/build_rdkitjs.sh`
22 error Exit status 1
23 error Failed at the @rdkit/rdkit@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Configuration (please complete the following information):**
 - RDKit version: latest
 - OS: m1 mac pro

**Comment by seongsangcho-hits** [comment]
use `docker buildx build --platform linux/amd64 -t build:0.5 ./` It is working.

m1 chip has build error, so if anybody encounter same error, consider using buildx to build docker file.

**Comment by seongsangcho-hits** [comment]
m1 chip(arm64) has this issue, so I used `platform` option that can build multi-architecture. so I used `linux/amd64` architecture build image, it was builded.

this is my docker oper.

DOCKER_BUILDKIT=1 docker build --platform  linux/amd64 -t compile:0.1 --no-cache -f ./Dockerfile --build-arg RDKIT_BRANCH=$RDKIT_BRANCH -o $MINIMALLIB_OUTPUT_PATH .

**Comment by MichelML** [comment]
@seongsangcho-hits did you know you can use the prebuilt, published version of the JS minimal lib on npm?

Here is the link including how to use it https://www.npmjs.com/package/@rdkit/rdkit

There is a release with every new rdkit release as well

**Comment by MichelML** [comment]
Readme on how to use it is also at https://github.com/rdkit/rdkit/blob/master/Code/MinimalLib/README.md

**Comment by greglandrum** [comment]
I'm closing this because it looks like the question is answered. Please reopen if necessary.
