### ISSUE TITLE
Bond additions may cause SMILES canonicalization to fail

### ISSUE THREAD

**Issue by AlanKerstjens** [rdkit/rdkit#5770]
**Describe the bug**
Certain (combinations of) bond additions cause SMILES canonicalization to fail.

**To Reproduce**
In the following snippets `RDKit::MolToSmiles` triggers two different exceptions:

```cpp
#include <GraphMol/RWMol.h>
#include <GraphMol/SmilesParse/SmilesParse.h>
#include <GraphMol/SmilesParse/SmilesWrite.h>

int main() {
  RDKit::RWMOL_SPTR molecule (RDKit::SmilesToMol("C/C=C/C=C/C"));
  molecule->addBond(1, 3, RDKit::Bond::DOUBLE);
  // Throws 'Invar::Invariant' "bad bond type"
  std::cout << RDKit::MolToSmiles(*molecule) << std::endl;
  return 0;
};
```
```cpp
#include <GraphMol/RWMol.h>
#include <GraphMol/SmilesParse/SmilesParse.h>
#include <GraphMol/SmilesParse/SmilesWrite.h>

int main() {
  RDKit::RWMOL_SPTR molecule (RDKit::SmilesToMol("C/C=C/C=C/C"));
  molecule->addBond(1, 3, RDKit::Bond::SINGLE);
  molecule->addBond(2, 4, RDKit::Bond::SINGLE);
  // Throws 'Invar::Invariant' "inconsistent state"
  std::cout << RDKit::MolToSmiles(*molecule) << std::endl;
  return 0;
};
```
*(Python examples below)*

**Expected behavior**
The canonical SMILES to be correctly generated.

**Configuration (please complete the following information):**
Reproduced on two systems with two different versions of the RDKit in both C++ and Python.

- RDKit Version: 2023.03.1pre & 2021.03.4
- Operating system: GNU/Linux Debian Bookworm & Ubuntu 20.04 LTS
- Python version (if relevant): 3.10.8
- Are you using conda? No
- How did you install the RDKit? From source

**Additional context**
I've tracked the issue down to SMILES canonicalization. Indeed, setting `canonical=false` prevents the issue. The issue seems to be related to bonding two atoms involved in double bonds. For example, it doesn't occur with `CCC/C=C/C`.

The issue does not occur when constructing the edited molecule from SMILES. For example, the following works:
```cpp
  RDKit::RWMOL_SPTR molecule (RDKit::SmilesToMol("CC1=C2C(C)=C12"));
  std::cout << RDKit::MolToSmiles(*molecule) << std::endl;
```

Python provides more informative error messages:

```python
from rdkit import Chem
molecule = Chem.RWMol(Chem.MolFromSmiles("C/C=C/C=C/C"))
molecule.AddBond(1, 3, Chem.BondType.DOUBLE)
print(Chem.MolToSmiles(molecule)) # Pre-condition violation "bad bond type"
```
Output:
```
****
Pre-condition Violation
bad bond type
Violation occurred on line 121 in file /home/alan/Libraries/rdkit/Code/GraphMol/Canon.cpp
Failed Expression: bond->getBondType() == Bond::SINGLE || bond->getIsAromatic()
****

Traceback (most recent call last):
  File "/home/alan/Code/Cheminformatics/test.py", line 151, in <module>
    print(Chem.MolToSmiles(molecule)) # Pre-condition violation "bad bond type"
RuntimeError: Pre-condition Violation
        bad bond type
        Violation occurred on line 121 in file Code/GraphMol/Canon.cpp
        Failed Expression: bond->getBondType() == Bond::SINGLE || bond->getIsAromatic()
        RDKIT: 2023.03.1pre
        BOOST: 1_74
```
```python
from rdkit import Chem
molecule = Chem.RWMol(Chem.MolFromSmiles("C/C=C/C=C/C"))
molecule.AddBond(1, 3, Chem.BondType.SINGLE)
molecule.AddBond(2, 4, Chem.BondType.SINGLE)
print(Chem.MolToSmiles(molecule)) # Invariant violation "inconsistent state"
```
Output:
```
****
Invariant Violation
inconsistent state
Violation occurred on line 310 in file /home/alan/Libraries/rdkit/Code/GraphMol/Canon.cpp
Failed Expression: ((firstFromAtom2->getBeginAtomIdx() == atom2->getIdx()) ^ (secondFromAtom2->getBeginAtomIdx() == atom2->getIdx()))
****

Traceback (most recent call last):
  File "/home/alan/Code/Cheminformatics/test.py", line 146, in <module>
    print(Chem.MolToSmiles(molecule)) # Invariant violation "inconsistent state"
RuntimeError: Invariant Violation
        inconsistent state
        Violation occurred on line 310 in file Code/GraphMol/Canon.cpp
        Failed Expression: ((firstFromAtom2->getBeginAtomIdx() == atom2->getIdx()) ^ (secondFromAtom2->getBeginAtomIdx() == atom2->getIdx()))
        RDKIT: 2023.03.1pre
        BOOST: 1_74
```

I'm aware that the edited molecules aren't chemically reasonable, but since it's possible to write out their non-canonical SMILES the fact that generating their canonical SMILES fails seems like a bug.

**Comment by bp-kelley** [comment]
Because you are mucking about with stereochemistry, you must force it to be reperceived, especially because the original stereochemistry is floating around which is causing the issue when the rdkit tries to canonicalize and hits the now invalid (at least to the RDKit) stereochemistry.


```
from rdkit import Chem
molecule = Chem.RWMol(Chem.MolFromSmiles("C/C=C/C=C/C"))
molecule.AddBond(1, 3, Chem.BondType.SINGLE)
molecule.AddBond(2, 4, Chem.BondType.SINGLE)
Chem.AssignStereochemistry(molecule, True, True, True)
print(Chem.MolToSmiles(molecule)) 
```

**Comment by bp-kelley** [comment]
```>>> help(Chem.AssignStereochemistry)
Help on built-in function AssignStereochemistry in module rdkit.Chem.rdmolops:

AssignStereochemistry(...)
    AssignStereochemistry( (Mol)mol [, (bool)cleanIt=False [, (bool)force=False [, (bool)flagPossibleStereoCenters=False]]]) -> None :
        Does the CIP stereochemistry assignment 
          for the molecule's atoms (R/S) and double bond (Z/E).
          Chiral atoms will have a property '_CIPCode' indicating
          their chiral code.
        
          ARGUMENTS:
        
            - mol: the molecule to use
            - cleanIt: (optional) if provided, any existing values of the property `_CIPCode`
                will be cleared, atoms with a chiral specifier that aren't
              actually chiral (e.g. atoms with duplicate substituents or only 2 substituents,
              etc.) will have their chiral code set to CHI_UNSPECIFIED. Bonds with 
              STEREOCIS/STEREOTRANS specified that have duplicate substituents based upon the CIP 
              atom ranks will be marked STEREONONE. 
            - force: (optional) causes the calculation to be repeated, even if it has already
              been done
            - flagPossibleStereoCenters (optional)   set the _ChiralityPossible property on
              atoms that are possible stereocenters
        
    
        C++ signature :
            void AssignStereochemistry(RDKit::ROMol {lvalue} [,bool=False [,bool=False [,bool=False]]])
```

**Comment by bp-kelley** [comment]
You should also probably update the property cache in general to fix valence issues when modifying molecules.

```
molecule.UpdatePropertyCache()
```

```
>>> help(molecule.UpdatePropertyCache)
Help on method UpdatePropertyCache:

UpdatePropertyCache(...) method of rdkit.Chem.rdchem.RWMol instance
    UpdatePropertyCache( (Mol)self [, (bool)strict=True]) -> None :
        Regenerates computed properties like implicit valence and ring information.
        
        
    
        C++ signature :
            void UpdatePropertyCache(RDKit::ROMol {lvalue} [,bool=True])
```

**Comment by bp-kelley** [comment]
Since this is not a bug, please move this to the discussions tab if you want to continue the conversation.

**Comment by AlanKerstjens** [comment]
@bp-kelley Thanks! I didn't know stereochemistry was used for canonicalization.
