### ISSUE TITLE
[GCC-13] Tests aborted

### ISSUE THREAD

**Issue by sagitter** [rdkit/rdkit#6494]
Hi all

**Describe the bug**

Many tests are failing when i build `RDKIT-2023-03-2` with an output like this:

```
/usr/include/c++/13/string_view:258: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.

        Start  61: testGeneralFileReader
  2/197 Test  #31: graphmolMolOpsTest .....................Subprocess aborted***Exception:   0.19 sec
```

**To Reproduce**
Building RDKIT on Fedora 38 64_bit with this CMake configuration:

`usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -D RDK_INSTALL_INTREE=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_SKIP_RPATH:BOOL=ON -D RDK_BUILD_INCHI_SUPPORT:BOOL=ON -D RDK_BUILD_THREADSAFE_SSS:BOOL=OFF -D RDK_BUILD_CAIRO_SUPPORT:BOOL=ON -D RDK_BUILD_DESCRIPTORS3D:BOOL=OFF -D RDK_BUILD_COORDGEN_SUPPORT:BOOL=OFF -D RDK_BUILD_MOLINTERCHANGE_SUPPORT:BOOL=OFF -D RDK_OPTIMIZE_POPCNT:BOOL=OFF -D DRDK_BUILD_CPP_TESTS:BOOL=ON -D RDK_BUILD_THREADSAFE_SSS:BOOL=ON -D RDK_BUILD_PGSQL:BOOL=ON -D PostgreSQL_ROOT:PATH=/usr -D PostgreSQL_TYPE_INCLUDE_DIR:PATH=/usr/include/pgsql/server -D RDK_PGSQL_STATIC:BOOL=OFF -D RDK_INSTALL_STATIC_LIBS:BOOL=OFF -D RDK_USE_FLEXBISON:BOOL=OFF -D RDK_TEST_MULTITHREADED:BOOL=ON -D PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -D RDK_BOOST_PYTHON3_NAME=python311 -D CATCH_DIR:FILEPATH=/usr/include/catch2 -D RDK_USE_URF:BOOL=OFF -D RDK_INSTALL_COMIC_FONTS:BOOL=OFF -D RDK_BUILD_SWIG_JAVA_WRAPPER:BOOL=OFF -D RDK_BUILD_SWIG_WRAPPERS=OFF`

**Configuration (please complete the following information):**
 - RDKit version: 2023.03.2
 - OS: Fedora 38
 - Python version (if relevant): `3.11.4` (and Python `3.12` in near future)

**Comment by sagitter** [comment]
This is the full build log: [rdkit_build.zip](https://github.com/rdkit/rdkit/files/11858052/rdkit_build.zip)

**Comment by bp-kelley** [comment]
A good place to check is the CI build scripts for how they work, I tend to copy these to do builds.

https://github.com/rdkit/rdkit/blob/master/.azure-pipelines/linux_build.yml

I'll see if I can duplicate your build to see what the specific issue is.

**Comment by sagitter** [comment]
> My guess is that somehow the system is mixing std::c++ libraries between build and test, the errors are specific to std::basic_string_view not rdkit itself. Could you check the dynamic links here?

`-D_GLIBCXX_ASSERTIONS` flag originates the issue you pointed, except the failure of `pyGraphMolWrap` that it's different probably.

```
191/197 Test #158: pyGraphMolWrap .........................***Failed   23.49 sec
..............[19:48:37] SMARTS Parse Error: syntax error while parsing: fiib
[19:48:37] SMARTS Parse Error: Failed parsing SMARTS 'fiib' for input: 'fiib'
....[19:48:37] ERROR: Problems encountered parsing data fields
[19:48:37] ERROR: moving to the beginning of the next molecule
[19:48:37] ERROR: Problems encountered parsing data fields
[19:48:37] ERROR: moving to the beginning of the next molecule
[19:48:37] Spurious data before the first property will be ignored
[19:48:37] Property <ID> will be truncated after the first blank line
[19:48:37] Property <ID> will be truncated after the first blank line
[19:48:37] Property <ANOTHER_PROPERTY> will be truncated after the first blank line
[19:48:37] ERROR: Problems encountered parsing data fields
[19:48:37] ERROR: moving to the beginning of the next molecule
[19:48:37] ERROR: Problems encountered parsing data fields
[19:48:37] ERROR: moving to the beginning of the next molecule
[19:48:37] Spurious data before the first property will be ignored
[19:48:37] Property <ID> will be truncated after the first blank line
[19:48:37] Property <ID> will be truncated after the first blank line
[19:48:37] Property <ANOTHER_PROPERTY> will be truncated after the first blank line
[19:48:37] ERROR: Problems encountered parsing data fields
[19:48:37] ERROR: moving to the beginning of the next molecule
[19:48:37] Property <ANOTHER_PROPERTY> will be truncated after the first blank line
[19:48:37] ERROR: Problems encountered parsing data fields
[19:48:37] ERROR: moving to the beginning of the next molecule
[19:48:37] Property <ANOTHER_PROPERTY> will be truncated after the first blank line
.[19:48:37] SMILES Parse Error: syntax error while parsing: fail
[19:48:37] SMILES Parse Error: Failed parsing SMILES 'fail' for input: 'fail'
[19:48:37] ERROR: Smiles parse error on line 2
[19:48:37] ERROR: Cannot create molecule from : 'fail'
>>> This may result in an infinite loop.  It should finish almost instantly
<<< OK, it finished.
............[19:48:37] Explicit valence for atom # 1 C, 5, is greater than permitted
........../home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Wrap/rough_test.py:2163: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals(ri.NumRings(), 2)
..[19:48:37] non-ring atom 0 marked aromatic
[19:48:37] non-ring atom 0 marked aromatic
[19:48:37] 

****
Range Error
idx
Violation occurred on line 213 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/ROMol.cpp
Failed Expression: 12 < 6
****

[19:48:37] non-ring atom 0 marked aromatic
[19:48:37] non-ring atom 0 marked aromatic
[19:48:37] 

****
Range Error
idx
Violation occurred on line 213 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/ROMol.cpp
Failed Expression: 12 < 6
****

...............[19:48:37] WARNING: the onlyHeavy argument to mol.GetNumAtoms() has been deprecated. Please use the onlyExplicit argument instead or mol.GetNumHeavyAtoms() if you want the heavy atom count.
[19:48:37] WARNING: the onlyHeavy argument to mol.GetNumAtoms() has been deprecated. Please use the onlyExplicit argument instead or mol.GetNumHeavyAtoms() if you want the heavy atom count.
..............[19:48:37] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
[19:48:37] Explicit valence for atom # 1 C, 5, is greater than permitted
...........................[19:48:44]  unable to set wavy bonds for double bonds: 3
.........[19:48:44] 

****
Range Error
idx
Violation occurred on line 213 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/ROMol.cpp
Failed Expression: 6 < 5
****

...................[19:48:47] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:47] Explicit valence for atom # 6 F, 2, is greater than permitted
[19:48:47] Can't kekulize mol.  Unkekulized atoms: 3 4 5
.[19:48:47] Warning: molecule is tagged as 3D, but all Z coords are zero
[19:48:47] Warning: molecule is tagged as 3D, but all Z coords are zero
[19:48:47] Warning: molecule is tagged as 3D, but all Z coords are zero
[19:48:47] Warning: molecule is tagged as 3D, but all Z coords are zero
[19:48:47] Warning: molecule is tagged as 3D, but all Z coords are zero
[19:48:47] Warning: molecule is tagged as 3D, but all Z coords are zero
...............[19:48:58] 

****
Pre-condition Violation
no owner
Violation occurred on line 138 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Atom.h
Failed Expression: dp_mol
****

[19:48:58] 

****
Pre-condition Violation
no owner
Violation occurred on line 138 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Atom.h
Failed Expression: dp_mol
****

[19:48:58] 

****
Pre-condition Violation
no owner
Violation occurred on line 138 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Atom.h
Failed Expression: dp_mol
****

[19:48:58] 

****
Pre-condition Violation
no owner
Violation occurred on line 138 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Atom.h
Failed Expression: dp_mol
****

[19:48:58] 

****
Pre-condition Violation
no owner
Violation occurred on line 138 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Atom.h
Failed Expression: dp_mol
****

.....[19:48:58] 

****
Range Error
atomIdx1
Violation occurred on line 375 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/RWMol.cpp
Failed Expression: 0 < 0
****

......[19:48:58] SMILES Parse Error: unclosed ring for input: 'c1ccccc'
[19:48:58] ERROR: Smiles parse error on line 0
[19:48:58] ERROR: Cannot create molecule from : 'c1ccccc'
[19:48:58] SMILES Parse Error: extra open parentheses for input: 'C(C'
[19:48:58] ERROR: Smiles parse error on line 3
[19:48:58] ERROR: Cannot create molecule from : 'C(C'
[19:48:58] Explicit valence for atom # 1 C, 5, is greater than permitted
[19:48:58] ERROR: Could not sanitize molecule on line 6
[19:48:58] ERROR: Explicit valence for atom # 1 C, 5, is greater than permitted
[19:48:58] SMILES Parse Error: unclosed ring for input: 'c1ccccc'
[19:48:58] ERROR: Smiles parse error on line 0
[19:48:58] ERROR: Cannot create molecule from : 'c1ccccc'
[19:48:58] SMILES Parse Error: extra open parentheses for input: 'C(C'
[19:48:58] ERROR: Smiles parse error on line 3
[19:48:58] ERROR: Cannot create molecule from : 'C(C'
[19:48:58] SMILES Parse Error: unclosed ring for input: 'C1C(Cl)CCCC'
[19:48:58] ERROR: Smiles parse error on line 6
[19:48:58] ERROR: Cannot create molecule from : 'C1C(Cl)CCCC'
[19:48:58] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:58] ERROR: Could not sanitize molecule ending on line 21
[19:48:58] ERROR: Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:58] ERROR: EOF hit while reading atoms
[19:48:58] ERROR: moving to the beginning of the next molecule
[19:48:58] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:58] ERROR: Could not sanitize molecule ending on line 21
[19:48:58] ERROR: Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:58] ERROR: EOF hit while reading atoms
[19:48:58] ERROR: moving to the beginning of the next molecule
....[19:48:58] 

****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 169 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****

........[19:48:58] 

****
Range Error
idx
Violation occurred on line 213 in file /home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/ROMol.cpp
Failed Expression: 3 < 1
****

..[19:48:58] Can't kekulize mol.  Unkekulized atoms: 0 1 2 3 4
..........FE............[19:48:58] SMILES Parse Error: unclosed ring for input: 'C1CC'
......[19:48:58] WARNING: not removing hydrogen atom without neighbors
[19:48:58] WARNING: not removing hydrogen atom with dummy atom neighbors
[19:48:58] WARNING: not removing hydrogen atom with wedged bond
[19:48:58] WARNING: not removing hydrogen atom without neighbors
[19:48:58] WARNING: not removing hydrogen atom with dummy atom neighbors
.....[19:48:59] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:59] Can't kekulize mol.  Unkekulized atoms: 0 1 2
.[19:48:59] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:59] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:59] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:59] Explicit valence for atom # 1 F, 2, is greater than permitted
[19:48:59] Can't kekulize mol.  Unkekulized atoms: 0 1 2
[19:48:59] Can't kekulize mol.  Unkekulized atoms: 0 1 2
[19:48:59] Can't kekulize mol.  Unkekulized atoms: 0 1 2
..........[19:48:59] SMARTS Parse Error: syntax error while parsing: CCC |$foo;;bar$| ourname
[19:48:59] SMARTS Parse Error: Failed parsing SMARTS 'CCC |$foo;;bar$| ourname' for input: 'CCC |$foo;;bar$| ourname'
.[19:48:59] SMILES Parse Error: syntax error while parsing: CCC |$foo;;bar$| ourname
[19:48:59] SMILES Parse Error: Failed parsing SMILES 'CCC |$foo;;bar$| ourname' for input: 'CCC |$foo;;bar$| ourname'
..[19:48:59] SMILES Parse Error: syntax error while parsing: error
[19:48:59] SMILES Parse Error: Failed parsing SMILES 'error' for input: 'error'
[19:48:59] SMILES Parse Error: Failed parsing SMILES 'd' for input: 'd'
[19:48:59] SMARTS Parse Error: Failed parsing SMARTS 'error' for input: 'error'
[19:48:59] SMARTS Parse Error: Failed parsing SMARTS 'd' for input: 'd'
..............[19:48:59] SMILES Parse Error: syntax error while parsing: garbage_0
[19:48:59] SMILES Parse Error: Failed parsing SMILES 'garbage_0' for input: 'garbage_0'
[19:48:59] SMILES Parse Error: syntax error while parsing: garbage_2
[19:48:59] SMILES Parse Error: Failed parsing SMILES 'garbage_2' for input: 'garbage_2'
[19:48:59] SMILES Parse Error: syntax error while parsing: garbage_4
[19:48:59] SMILES Parse Error: Failed parsing SMILES 'garbage_4' for input: 'garbage_4'
..........
======================================================================
ERROR: testMaeWriterRoundtrip (__main__.TestCase.testMaeWriterRoundtrip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Wrap/rough_test.py", line 7182, in testMaeWriterRoundtrip
    roundtrip_mol = next(r)
                    ^^^^^^^
RuntimeError: File parsing error: Bad floating point representation.

======================================================================
FAIL: testMaeWriterProps (__main__.TestCase.testMaeWriterProps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sagitter/rpmbuild/BUILD/rdkit-Release_2023_03_2/Code/GraphMol/Wrap/rough_test.py", line 7154, in testMaeWriterProps
    self.assertIn(str(realProp), line)
AssertionError: '2.718282' not found in '    3 -0,750000 -1,299038 0,000000 2,718282 6 0 767676 "This is a dummy prop, yay!"'

----------------------------------------------------------------------
Ran 241 tests in 22.736s

FAILED (failures=1, errors=1)
1
supplier: <class 'rdkit.Chem.rdmolfiles.SmilesMolSupplier'>
supplier: <class 'rdkit.Chem.rdmolfiles.SDMolSupplier'>
supplier: <class 'rdkit.Chem.rdmolfiles.TDTMolSupplier'>
```
