### ISSUE TITLE
Simple imine-containing molecule causes an infinite loop in FindStereo.cpp

### ISSUE THREAD

**Issue by ptosco** [rdkit/rdkit#6640]
With current RDKit master, the following Python snippet causes an infinite loop:

```
from rdkit import Chem

Chem.SetUseLegacyStereoPerception(False)
mol = Chem.MolFromSmiles('NC1=NC(=N)N=C(N)C1C')
```

`gdb` shows that the infinite loop takes place in `runCleanup` at line 1053 inside `FindStereo.cpp`, as `updateBonds()` always returns `true`:
```
#5  RDKit::Chirality::(anonymous namespace)::updateBonds (mol=..., aranks=..., bondSymbols=..., possibleAtoms=..., possibleBonds=..., knownAtoms=..., knownBonds=..., fixedBonds=..., sinfos=...)
    at /scratch/toscopa1/src/rdkit/Code/GraphMol/FindStereo.cpp:827
#6  0x00007fffec6a1213 in RDKit::Chirality::(anonymous namespace)::runCleanup (mol=..., flagPossible=<optimized out>, cleanIt=<optimized out>) at /scratch/toscopa1/src/rdkit/Code/GraphMol/FindStereo.cpp:1053
#7  0x00007fffec6a17e6 in RDKit::Chirality::findPotentialStereo (mol=..., cleanIt=cleanIt@entry=true, findPossible=findPossible@entry=true) at /scratch/toscopa1/src/rdkit/Code/GraphMol/FindStereo.cpp:1073
#8  0x00007fffec64e32b in RDKit::Chirality::stereoPerception (mol=..., cleanIt=<optimized out>, flagPossibleStereoCenters=<optimized out>) at /scratch/toscopa1/src/rdkit/Code/GraphMol/Chirality.cpp:2175
#9  0x00007fffec65ff06 in RDKit::MolOps::assignStereochemistry (mol=..., cleanIt=<optimized out>, force=<optimized out>, flagPossibleStereoCenters=<optimized out>) at /scratch/toscopa1/src/rdkit/Code/GraphMol/Chirality.cpp:2206
#10 0x00007fffec7a3388 in RDKit::SmilesToMol (smiles=..., params=...) at /scratch/toscopa1/src/rdkit/Code/GraphMol/SmilesParse/SmilesParse.cpp:454
#11 0x00007fffec13dacf in RDKit::SmilesToMol (replacements=0x7fffffff9520, sanitize=true, debugParse=0, smi=...) at /scratch/toscopa1/src/rdkit/Code/GraphMol/SmilesParse/SmilesParse.h:81
#12 RDKit::MolFromSmiles (ismiles=..., sanitize=<optimized out>, replDict=...) at /scratch/toscopa1/src/rdkit/Code/GraphMol/Wrap/rdmolfiles.cpp:74
```

I managed to track down the cause of the regression, which was introduced by #6473 and the follow-up PR #6527.
@ricrogz Would you have time to take a look? Many thanks in advance!

**Comment by ricrogz** [comment]
> @ricrogz Would you have time to take a look? Many thanks in advance!

Sure, I'll have a look.
