### ISSUE TITLE
No to_python (by-value) converter found

### ISSUE THREAD

**Issue by rmcgibbo** [rdkit/rdkit#667]
Hi,

I'm seeing the following error on import, with the latest release (2015_09_1). This is with boost 1.59, `Boost_USE_STATIC_LIBS=ON`, linux amd64 (centos5), gcc 4.8.2. Any suggestions would be appreciated.

```
Traceback (most recent call last):
  File "run_test.py", line 43, in <module>
    import rdkit.Chem
  File "/anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Chem/__init__.py", line 22, in <module>
    from rdkit.Geometry import rdGeometry
  File "/anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/__init__.py", line 5, in <module>
    from rdkit.Geometry.rdGeometry import *
TypeError: No to_python (by-value) converter found for C++ type: RDKit::DiscreteValueVect::DiscreteValue
```

**Comment by greglandrum** [comment]
Did you do the build using the conda-rdkit recipes or from the command line?

**Comment by rmcgibbo** [comment]
No, I didn't use the conda-rdkit recipe.

**Comment by greglandrum** [comment]
If you are using the RDKit as a toolkit to build on top of/with (as opposed to doing RDKit development), it might be worth taking a look at those (there are build instructions in the new version of the RDKit docs).

If you still want to build yourself, here are some thoughts about tracking this problem down:
I have seen this type of error occur when you have different versions of the code being used simultaneously.
Try looking at which libraries are being used by the libraries:
ldd /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/rdGeometry.so
ldd /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/DataStructs/cDataStructs.so

**Comment by rmcgibbo** [comment]
I don't see anything strange.
```
$ ldd /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/rdGeometry.so
	linux-vdso.so.1 =>  (0x00007ffe89d89000)
	libRDGeometryLib.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/../../../../libRDGeometryLib.so.1 (0x00007f3dac865000)
	libDataStructs.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/../../../../libDataStructs.so.1 (0x00007f3dac580000)
	libRDGeneral.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/../../../../libRDGeneral.so.1 (0x00007f3dac353000)
	libRDBoost.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/../../../../libRDBoost.so.1 (0x00007f3dac14b000)
	libpython2.7.so.1.0 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/Geometry/../../../../libpython2.7.so.1.0 (0x00007f3dabd68000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3daba59000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3dab751000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3dab53b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3dab171000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3daaf53000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3daad4f000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f3daab4c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3dacd66000
$ ldd /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/DataStructs/cDataStructs.so
	linux-vdso.so.1 =>  (0x00007fff80ddd000)
	libDataStructs.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/DataStructs/../../../../libDataStructs.so.1 (0x00007ff27d053000)
	libRDBoost.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/DataStructs/../../../../libRDBoost.so.1 (0x00007ff27ce4b000)
	libpython2.7.so.1.0 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/DataStructs/../../../../libpython2.7.so.1.0 (0x00007ff27ca68000)
	libRDGeneral.so.1 => /anaconda/envs/_test/lib/python2.7/site-packages/rdkit/DataStructs/../../../../libRDGeneral.so.1 (0x00007ff27c83b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff27c52c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff27c224000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff27c00e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff27bc44000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff27ba26000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff27b822000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007ff27b61f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff27d6d5000)
```

**Comment by greglandrum** [comment]
Looking at those, I finally realize the significance of your remark that you are using `Boost_USE_STATIC_LIBS=ON`. This could cause a problem because of the way type conversion is handled between python modules (the global map between types and converters may end up not actually being global). Please try turning that OFF (or not explicitly setting it to be ON when you invoke cmake) and see if the problem still occurs.

**Comment by rmcgibbo** [comment]
> Please try turning that OFF (or not explicitly setting it to be ON when you invoke cmake) and see if the problem still occurs.

The problem does not occur when I dynamically link to boost. But if possible, I'd really prefer to statically link to boost. Is static linking on linux a supported configuration?

**Comment by greglandrum** [comment]
I believe that it's not possible with boost::python, but I've never investigated this.

**Comment by rmcgibbo** [comment]
If that's the case, then you might consider turning off the option in CMake.
