### ISSUE TITLE
Using anaconda to install, ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by EricTing** [rdkit/rdkit#680]
I followed the instructions (https://github.com/rdkit/rdkit/blob/master/Docs/Book/Install.md) and completed the installation of _rdkit_ using _anaconda_.
It showed:

```
Fetching package metadata: ...
Solving package specifications: .................
Package plan for installation in environment /home/jaydy/envs/my-rdkit-env:

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    boost-1.56.0               |           py27_3   hard-link
    bzip2-1.0.6                |                0   hard-link
    mkl-rt-11.1                |               p0   hard-link
    numpy-1.10.1               |          py27_p0   hard-link
    openssl-1.0.2d             |                0   hard-link
    python-2.7.10              |                2   hard-link
    rdkit-2015.09.2            |      np110py27_0   hard-link
    readline-6.2               |                2   hard-link
    sqlite-3.8.4.1             |                1   hard-link
    tk-8.5.18                  |                0   hard-link
    zlib-1.2.8                 |                0   hard-link

Proceed ([y]/n)? y

Extracting packages ...
[      COMPLETE      ] |#######################################################################################################| 100%
Linking packages ...
[      COMPLETE      ] |#######################################################################################################| 100%
```

Then I activated the python virtual env using `$ source activate my-rdkit-env` and tried to use it:
```
(/home/jaydy/envs/my-rdkit-env)[jaydy@qb2 ~]$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:04:42)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from rdkit import Chem
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaydy/envs/my-rdkit-env/lib/python2.7/site-packages/rdkit/Chem/__init__.py", line 28, in <module>
    from rdkit.Chem.rdmolops import *
ImportError: numpy.core.multiarray failed to import
>>>
```

The issue seems to be caused by a version of `numpy` that is not compatible with the current setup of rdkit. Anyone knows how to address it?

I am using the supercomputer in my university and do not have the root. Of corse I can try to install everything from scratch in my /home but that would be a nightmare.

**Comment by EricTing** [comment]
The issue is resolved by using the *latest Anaconda 2.7*
