### ISSUE TITLE
Many tests fail

### ISSUE THREAD

**Issue by yurivict** [rdkit/rdkit#7779]
**Describe the bug**
See the [log](https://freebsd.org/~yuri/rdkit-2024_03_6-failing-LastTest.log).

**To Reproduce**
Regular tess run.

**Configuration (please complete the following information):**
 - RDKit version: 2024_03_6
 - OS: FreeBSD 14.1
 - Python version (if relevant): 3.11
 - Are you using conda? no

**Comment by greglandrum** [comment]
Hi @yurivict. There's something strange going on here. Did 2024.03.5 work in exactly the same configuration (same compiler, cmake flags, etc?)

**Comment by yurivict** [comment]
@greglandrum 

We didn't try ```2024.03.5```. In fact, we didn't run tests for previous versions.

**Comment by greglandrum** [comment]
The tests that are failing are very basic and are not connected to any recent changes.
A lot of the failures seem to be connected with problems in translating exceptions, so I wonder if it's somehow possible that the RDKit python wrappers were built using a different boost::python build than what's being used at runtime?

Do you have logs showing the cmake command used along with the output it generates?

**Comment by yurivict** [comment]
[Here](https://freebsd.org/~yuri/rdkit-2024_03_6-build+test.log) is a complete log.

**Comment by yurivict** [comment]
rdkit-2024.09.4 is still broken in the same way.

When I've ran Code/Geometry/Wrap/testGeometry.py it fails:
```
$ python3.11 ./work/rdkit-Release_2024_09_4/Code/Geometry/Wrap/testGeometry.py 
Testing Geometry wrapper
...EEEYURI: v1.getValueType()=1
YURI: v2.getValueType()=2
E.............
======================================================================
ERROR: test1aPoint3D (__main__.TestCase.test1aPoint3D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/rdkit/./work/rdkit-Release_2024_09_4/Code/Geometry/Wrap/testGeometry.py", line 37, in test1aPoint3D
    lst = list(pt)
          ^^^^^^^^
RuntimeError: Index Error: 3

======================================================================
ERROR: test1bPoint2D (__main__.TestCase.test1bPoint2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/rdkit/./work/rdkit-Release_2024_09_4/Code/Geometry/Wrap/testGeometry.py", line 424, in test1bPoint2D
    lst = list(pt)
          ^^^^^^^^
RuntimeError: Index Error: 2

======================================================================
ERROR: test1cPointND (__main__.TestCase.test1cPointND)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/rdkit/./work/rdkit-Release_2024_09_4/Code/Geometry/Wrap/testGeometry.py", line 478, in test1cPointND
    lst = list(pt)
          ^^^^^^^^
RuntimeError: Index Error: 4

======================================================================
ERROR: test3UniformGrid (__main__.TestCase.test3UniformGrid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/rdkit/./work/rdkit-Release_2024_09_4/Code/Geometry/Wrap/testGeometry.py", line 562, in test3UniformGrid
    self.assertRaises(ValueError, lambda: geom.TanimotoDistance(grd, grd2))
  File "/usr/local/lib/python3.11/unittest/case.py", line 766, in assertRaises
    return context.handle('assertRaises', args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/case.py", line 237, in handle
    callable_obj(*args, **kwargs)
  File "/usr/ports/science/rdkit/./work/rdkit-Release_2024_09_4/Code/Geometry/Wrap/testGeometry.py", line 562, in <lambda>
    self.assertRaises(ValueError, lambda: geom.TanimotoDistance(grd, grd2))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Comparing vector of different value types

----------------------------------------------------------------------
Ran 20 tests in 0.054s

FAILED (errors=4)
```

The error ```Comparing vector of different value types``` comes from computeL1Norm in Code/DataStructs/DiscreteValueVect.cpp where these printouts:
```
@@ -102,6 +103,8 @@ unsigned int computeL1Norm(const DiscreteValueVect &v1
   DiscreteValueVect::DiscreteValueType valType = v1.getValueType();

   if (valType != v2.getValueType()) {
+    std::cout << "v1.getValueType()=" << v1.getValueType() << std::endl;
+    std::cout << "v2.getValueType()=" << v2.getValueType() << std::endl;
     throw ValueErrorException("Comparing vector of different value types");
   }
```

print that types are different:
```
v1.getValueType()=1
v2.getValueType()=2
```

If something is wrong with dependencies - cmake should catch that, but it doesn't complain.

**Comment by yurivict** [comment]
2025_03_1 still has many failures, like previous versions.

**Comment by greglandrum** [comment]
@yurivict I'd love to help you fix the your build configuration, but I have not been able to reproduce this on linux-based systems.
I also have not managed to figure out how to get a VM running FreeBSD up in order to be able to reproduce it.
Any hints you may have on how to do this would be welcome

**Comment by yurivict** [comment]
> Is there an easy way to test under FreeBSD?

```
1. Install the [FreeBSD VM image](https://download.freebsd.org/ftp/releases/VM-IMAGES/14.2-RELEASE/amd64/Latest/) into VirtualBox.
2. Boot FreeBSD
3. Install git: pkg install git
4. Check out the ports tree: git clone https://git.FreeBSD.org/ports.git /usr/ports
5. cd /usr/ports/science/rdkit
6. Install dependencies: pkg install -A `make missing`
7. Build: make
8. Run tests: make test
```

**Comment by vedranmiletic** [comment]
@greglandrum FWIW, since 14.3-RELEASE, FreeBSD is also available as a Docker image, which might be easier to run than a full VM: https://hub.docker.com/u/freebsd

**Comment by vedranmiletic** [comment]
> [@greglandrum](https://github.com/greglandrum) FWIW, since 14.3-RELEASE, FreeBSD is also available as a Docker image, which might be easier to run than a full VM: https://hub.docker.com/u/freebsd

Please disregard this, I wrongly assumed this works everywhere when I ran it with Podman on FreeBSD, it's not an option if the host OS is something else.
