### ISSUE TITLE
Segfaults in python on 32-bit (i386/armel/armhf)

### ISSUE THREAD

**Issue by mbanck** [rdkit/rdkit#8051]
**Describe the bug**

Running `from rdkit import Chem` leads to a segfault on 32-bit architectures (Debian architectures i386 armel and armhf), see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1083076 or the build logs that show all python-based tests failing, e.g. this one: https://buildd.debian.org/status/fetch.php?pkg=rdkit&arch=i386&ver=202409.2-2&stamp=1732738941&raw=0

**To Reproduce**
Install RDKit on 32-bit i386, go into python, execute `from rdkit import Chem`

**Expected behavior**
Importing rdkit/Chem works fine

**Screenshots**
```
(sid_armel-dchroot)mbanck@amdahl:~$ python3
Python 3.12.7 (main, Nov  8 2024, 17:55:36) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Segmentation fault
(sid_armel-dchroot)mbanck@amdahl:~$ 
```

**Configuration (please complete the following information):**
 - RDKit version: 202409.2
 - OS: Debian unstable
 - Python version (if relevant): 3.12.7 
 - Are you using conda? no
 - If you are using conda, which channel did you install the rdkit from? n/a
 - If you are not using conda: how did you install the RDKit? Debian package

**Additional context**

Backtrace (first ten frames):

```
(gdb) bt
#0  0xf79c833c in boost::python::objects::enum_base::add_value(char const*, long) () from /lib/arm-linux-gnueabi/libboost_python312.so.1.83.0
#1  0xf5311144 in boost::python::enum_<RDKit::SmilesWrite::CXSmilesFields>::value (this=0xfffed910, name=0xf53a1fc4 "CX_ALL", x=RDKit::SmilesWrite::CX_ALL) at /usr/include/boost/python/enum.hpp:93
#2  init_module_rdmolfiles () at ./Code/GraphMol/Wrap/rdmolfiles.cpp:1725
#3  0xf79d5dd4 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /lib/arm-linux-gnueabi/libboost_python312.so.1.83.0
#4  0xf5f4b288 in boost::python::detail::translate_exception<RDKit::CIPLabeler::MaxIterationsExceeded, void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)>::operator() (this=<optimized out>, handler=..., 
    f=..., translate=0xf5f49d4c <rdMaxIterationsExceededTranslator(RDKit::CIPLabeler::MaxIterationsExceeded const&)>) at /usr/include/boost/python/detail/translate_exception.hpp:39
#5  boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)> >::operator()<bool, boost::python::detail::translate_exception<RDKit::CIPLabeler::MaxIterationsExceeded, void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (this=<optimized out>, 
    f=..., a=<synthetic pointer>...) at /usr/include/boost/bind/bind.hpp:368
#6  boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::CIPLabeler::MaxIterationsExceeded, void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (this=<optimized out>, 
    a1=..., a2=...) at /usr/include/boost/bind/bind.hpp:1298
#7  boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::CIPLabeler::MaxIterationsExceeded, void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::CIPLabeler::MaxIterationsExceeded const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...) at /usr/include/boost/function/function_template.hpp:137
#8  0xf5c74fc4 in boost::python::detail::translate_exception<RDKit::ConformerException, void (*)(RDKit::ConformerException const&)>::operator() (this=<optimized out>, handler=..., f=..., 
    translate=0xf5bf48d4 <rdExceptionTranslator(RDKit::ConformerException const&)>) at /usr/include/boost/python/detail/translate_exception.hpp:39
#9  boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::ConformerException const&)> >::operator()<bool, boost::python::detail::translate_exception<RDKit::ConformerException, void (*)(RDKit::ConformerException const&)>, boost::_bi::rrlist2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (this=<optimized out>, f=..., a=<synthetic pointer>...)
    at /usr/include/boost/bind/bind.hpp:368
#10 boost::_bi::bind_t<bool, boost::python::detail::translate_exception<RDKit::ConformerException, void (*)(RDKit::ConformerException const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(RDKit::ConformerException const&)> > >::operator()<boost::python::detail::exception_handler const&, boost::function0<void> const&> (this=<optimized out>, a1=..., a2=...)
    at /usr/include/boost/bind/bind.hpp:1298
```

**Comment by greglandrum** [comment]
@mbanck thanks for reporting this.
I'm not quite sure how I can reproduce it since I don't have access to a 32bit machine.

I'm trying to figure out how important this is... do you have any sense for how many people are using debichem on 32bit architectures?

**Comment by mbanck** [comment]
Another point is that RDKIt is a build dependency for quite a few other packages, and it would mean having to adjust them to be 64bit-only as well if 32bit is dropped
