### ISSUE TITLE
Problems installing RDKit for Windows 7 and Linux

### ISSUE THREAD

**Issue by raulmendez** [rdkit/rdkit#813]
I have started to use your fantastic too RDKit, through the python interface and I have experienced installation problems both, when trying to install on Windows 7 (AMD 64 bit) and on Linux:

1) On Windows:

I did :

conda create -c https://conda.anaconda.org/rdkit -n my-rdkit-env rdkit

and instead of getting the 2015 version it downloads and isntall the rdkit-2014.09.2 . Then :

Python 2.7.11 |Continuum Analytics, Inc.| (default, Jan 29 2016, 14:26:21) [MSC
v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > from rdkit import Chem
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Miniconda2\envs\my-rdkit-env\lib\site-packages\rdkit\Chem__init__.py
> > > ", line 18, in <module>
> > >     from rdkit import rdBase
> > > ImportError: DLL load failed: The specified module could not be found.

And I have checked that C:\Miniconda2\envs\my-rdkit-env\Lib\site-packages\rdkit__init__.py is empty.

2) On linux, at the university cluster, there seem to be incompatibility with the libraries:

Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

> > > from rdkit import Chem
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/nas02/home/r/m/rmendez/Work/Software/miniconda/envs/my-rdkit-env/lib/python2.7/site-packages/rdkit/Chem/**init**.py", line 18, in <module>
> > >     from rdkit import rdBase
> > > ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /nas02/home/r/m/rmendez/Work/Software/miniconda/envs/my-rdkit-env/lib/python2.7/site-packages/rdkit/rdBase.so)

Can you please fix the distritbution for Windows, and provide suggestion for Linux ?

Thanks so much in advance,

Raul

Raul Mendez Giraldez, PhD
Dept. Epidemiology
UNC School of Public Health
Phone: 919-966-4596
137 East Franklin Street,
306G CVS Plaza Building
Chapel Hill, NC 27599 - 8050
USA

**Comment by rvianello** [comment]
As a shortest-term workaround to the problem on win7, could you please try specifying the rdkit version on the conda command-line as discussed in this thread?

https://sourceforge.net/p/rdkit/mailman/message/34936589/

I will try repackaging the old windows releases that are available from anaconda.org during the next days, but in the meantime the above link should hopefully help.

What linux version is installed on the cluster nodes? the rdkit conda packages are built using a centos6 docker container and may not work on older linux variants.

**Comment by raulmendez** [comment]
Ok, thank you Ricardo, this solved the problem in Windows. The problem in Linux still remains.

Raul

**Comment by bp-kelley** [comment]
@raulmendez what version of linux are you running?

C++ and GLIBC are notoriously hard to get working together and the build matrices can be quite complicated.  At some point it may be easier for you to build RDKit directly your platform.

Fortunately, this is relatively easy using conda, see here for details: https://github.com/rdkit/conda-rdkit
